/* should generate diagnostics */
Promise.reject();
Promise.reject(undefined);
Promise.reject(5);
Promise.reject("failure");
Promise.reject(`failure ${reason}`);
Promise.reject(false);
Promise.reject(null);
Promise.reject(5n);
Promise.reject(/error/);
Promise.reject({ message: "failure" });
Promise.reject([new Error()]);
Promise.reject(() => new Error());
Promise.reject(function() {});
Promise.reject(class {});
Promise.reject(!error);
Promise.reject(void error);
Promise.reject(error + "failure");
Promise.reject(error instanceof Error);
Promise.reject("message" in error);
Promise.reject(error++);
Promise.reject(++error);
Promise.reject(error && 5);
Promise.reject(5 || "failure");
Promise.reject(null ?? "failure");
Promise.reject(condition ? 5 : "failure");
Promise.reject((error, 5));
Promise.reject(error = 5);
Promise.reject(error &&= 5);
Promise.reject(error += new Error());
Promise.reject(error -= new Error());
Promise.reject(error **= new Error());
Promise.reject(error <<= new Error());
Promise.reject(error |= new Error());
Promise.reject(error &= new Error());
Promise.reject("failure", error);
Promise["reject"](5);
Promise[`reject`](5);
Promise.reject?.(5);
Promise?.reject(5);
Promise?.reject?.(5);
(Promise?.reject)(5);
(Promise?.reject)?.(5);
(Promise).reject((5));
new Promise((resolve, reject) => reject(5));
new Promise((resolve, reject) => reject());
new Promise(function(yes, no) { no("failure"); });
new Promise(({ value }, reject) => reject(5));
new Promise(({}, reject) => reject(5));
new Promise((resolve, reject, extra = reject(5)) => {});
new Promise((resolve, reject) => {
    readFile("file", (error, content) => {
        if (error) reject("File not found");
        else resolve(content);
    });
});
new (Promise)((((resolve, reject) => (reject)?.(5))));
new Promise(((function(resolve, reject) { reject(5); })));
