Object()
Array()
ArrayBuffer()
BigInt64Array()
BigUint64Array()
DataView()
Date()
Error()
Float32Array()
Float64Array()
Function()
Int8Array()
Int16Array()
Int32Array()
Map()
WeakMap()
Set()
WeakSet()
Promise()
RegExp()
Uint8Array()
Uint16Array()
Uint32Array()
Uint8ClampedArray()
SharedArrayBuffer()
Proxy()
WeakRef()
FinalizationRegistry()
window.Object({})
globalThis.Object()
function foo() {
    return /** Start */ globalThis.Object({ foo: 'bar' }) /** End */
}

new Boolean()
new BigInt()
new Number()
new String()
new Symbol()
new window.String(123)
new globalThis.String()
function foo() {
    return /** Start */ new globalThis.String("foo") /** End */
}