import type { T1 } from "bun:test"
import type { T2 } from "node:test"
import type { T3 } from "@scopeX/special/subpath"
import type { T4 } from "@scopeX/special"
import { v1 } from "bun:test"
import { v2 } from "node:test"
import { v3 } from "@scopeX/special/subpath"
import { v4 } from "@scopeX/special"
import { v5 } from "@scopeX/lib"
import { v6 } from "@scopeA/lib"
import { v7 } from "@scopeB/lib"
import type { T5 } from "@scopeX/lib"
import type { T6 } from "@scopeA/lib"
import type { T7 } from "@scopeB/lib"
