version: 1
allowed-users:
  - dyc3
trusted-author-associations:
  - owner
  - member
honeypot: true
messages:
  honeypot: |-
    A maintainer will take a look as soon as they can. In the meantime, please make sure that:

    - the description follows our PR template
    - any related issues are linked
    - existing tests still pass
