<label for="js_id" />;
<label for="js_id"><input /></label>;
<label for="js_id"><textarea /></label>;
<label htmlFor="js_id" />;
<label htmlFor="js_id"><input /></label>;
<label htmlFor="js_id"><textarea /></label>;
<label></label>;
<label>A label</label>;
<div><label /><input /></div>;
<div><label>A label</label><input /></div>;
