use crate::kinds_src::KindsSrc;

pub const CSS_KINDS_SRC: KindsSrc = KindsSrc {
    punct: &[
        (";", "SEMICOLON"),
        (",", "COMMA"),
        ("(", "L_PAREN"),
        (")", "R_PAREN"),
        ("{", "L_CURLY"),
        ("}", "R_CURLY"),
        ("[", "L_BRACK"),
        ("]", "R_BRACK"),
        ("<", "L_ANGLE"),
        (">", "R_ANGLE"),
        ("~", "TILDE"),
        ("#", "HASH"),
        ("&", "AMP"),
        ("|", "PIPE"),
        ("||", "PIPE2"),
        ("+", "PLUS"),
        ("*", "STAR"),
        ("/", "SLASH"),
        ("^", "CARET"),
        ("%", "PERCENT"),
        (".", "DOT"),
        (":", "COLON"),
        ("::", "COLON2"),
        ("=", "EQ"),
        ("!", "BANG"),
        ("!=", "NEQ"),
        ("-", "MINUS"),
        ("<=", "LTEQ"),
        (">=", "GTEQ"),
        ("+=", "PLUSEQ"),
        ("|=", "PIPEEQ"),
        ("&=", "AMPEQ"),
        ("^=", "CARETEQ"),
        ("/=", "SLASHEQ"),
        ("*=", "STAREQ"),
        ("%=", "PERCENTEQ"),
        ("@", "AT"),
        ("$=", "DOLLAR_EQ"),
        ("~=", "TILDE_EQ"),
        ("-->", "CDC"),
        ("<!--", "CDO"),
    ],
    keywords: &[
        "important",
    ],
    literals: &[
        "CSS_STRING_LITERAL",
        "CSS_NUMBER_LITERAL",
        "CSS_CUSTOM_PROPERTY",
        "CSS_SPACE_LITERAL",
        "CSS_FUNCTION_LITERAL"
    ],
    tokens: &[
        "ERROR_TOKEN",
        "NEWLINE",
        "WHITESPACE",
        "COMMENT",
        "MULTILINE_COMMENT",
        "FUNCTION_TOKEN",
        "IDENT",
        "AT_IDENT",
        "BAD_URL",
        "HASH_TOKEN",
        "URL",
        "DELIM",
        "UNICODE_RANGE",
    ],
    nodes: &[
        "CSS_STYLE_SHEET",
        "CSS_STYLE_SHEET_CONTENT",
        "CSS_QUALIFIED_RULE",
        "CSS_QUALIFIED_RULE_PRELUDE",
        "CSS_CURLY_BRACKETS_BLOCK",
        "CSS_CURLY_BRACKETS_BLOCK_CONTENT",
        "CSS_AT_RULE_COMPONENT_VALUE",
        "CSS_AT_RULE_CONTENT",
        "CSS_AT_RULE",
        "CSS_DECLARATION_LIST",
        "CSS_DECLARATION",
        "CSS_LIST_OF_COMPONENT_VALUE",
        "CSS_COMPONENT_VALUE",
        "CSS_DECLARATION_IMPORTANT",
        "CSS_SIMPLE_BLOCK",
        "CSS_FUNCTION_BLOCK",
        "CSS_SIMPLE_CURLY_BRACKETS_BLOCK",
        "CSS_SIMPLE_PARENTHESES_BLOCK",
        "CSS_SIMPLE_SQUARE_BRACKETS_BLOCK",
        "CSS_PRESERVED_TOKEN",
        "CSS_BLOCK_DECLARATION_LIST",
        "CSS_IDENTIFIER",
        "CSS_AT_KEYWORD",
        "CSS_FUNCTION_TOKEN",
        "CSS_STRING",
        "CSS_NUMBER",
        "CSS_COMPONENT_VALUE_LIST",
        "CSS_SIMPLE_COMPONENT_VALUE_LIST",
        "CSS_PERCENTAGE",
        "CSS_DIMENSION",
        "CSS_DELIM",
        "CSS_HASH",
        "CSS_PRESERVED_TOKEN_KEY",
        "CSS_AT_RULE_SEMICOLON",
        "CSS_BOGUS"
    ],
};
