use crate::kind_src::KindsSrc;

pub const GLIMMER_KINDS_SRC: KindsSrc = KindsSrc {
    punct: &[
        ("{{", "L_CURLY2"),
        ("}}", "R_CURLY2"),
        ("(", "L_PAREN"),
        (")", "R_PAREN"),
        ("<", "L_ANGLE"),
        (">", "R_ANGLE"),
        ("/", "SLASH"),
        (".", "DOT"),
        ("|", "PIPE"),
        ("=", "EQ"),
        ("#", "HASH"),
        ("@", "AT"),
    ],
    keywords: &[
        "as",
        "if",
        "else",
        "each",
        "let",
        "yield",
        "this",
        "true",
        "false",
        "null",
        "undefined",
    ],
    literals: &["GLIMMER_STRING_LITERAL", "GLIMMER_NUMBER_LITERAL"],
    tokens: &[
        "ERROR_TOKEN",
        "NEWLINE",
        "WHITESPACE",
        "IDENT",
        "TEXT",
        "COMMENT",
        "MUSTACHE_COMMENT",
    ],
    nodes: &[
        "GLIMMER_ROOT",
        "GLIMMER_BLOCK",
        "GLIMMER_TEXT_NODE",
        "GLIMMER_COMMENT_STATEMENT",
        "GLIMMER_MUSTACHE_COMMENT_STATEMENT",
        "GLIMMER_MUSTACHE_STATEMENT",
        "GLIMMER_BLOCK_STATEMENT",
        "GLIMMER_ELEMENT_NODE",
        "GLIMMER_START_TAG",
        "GLIMMER_END_TAG",
        "GLIMMER_ATTRIBUTE_NODE",
        "GLIMMER_ATTRIBUTE_VALUE",
        "GLIMMER_CONCAT_STATEMENT",
        "GLIMMER_ELEMENT_MODIFIER",
        "GLIMMER_BLOCK_PARAMS",
        "GLIMMER_PARAM_NAME",
        "GLIMMER_PATH_EXPRESSION",
        "GLIMMER_PATH_SEGMENT",
        "GLIMMER_THIS_HEAD",
        "GLIMMER_AT_HEAD",
        "GLIMMER_VAR_HEAD",
        "GLIMMER_SUB_EXPRESSION",
        "GLIMMER_HASH",
        "GLIMMER_HASH_PAIR",
        "GLIMMER_STRING_LITERAL",
        "GLIMMER_NUMBER_LITERAL",
        "GLIMMER_BOOLEAN_LITERAL",
        "GLIMMER_NULL_LITERAL",
        "GLIMMER_UNDEFINED_LITERAL",
        "GLIMMER_ELSE_BLOCK",
        "SELF_CLOSING",
        // Lists
        "GLIMMER_STATEMENT_LIST",
        "GLIMMER_ATTRIBUTE_LIST",
        "GLIMMER_CONCAT_PART_LIST",
        "GLIMMER_ELEMENT_MODIFIER_LIST",
        "GLIMMER_PARAM_NAME_LIST",
        "GLIMMER_PARAMS_LIST",
        "GLIMMER_PATH_SEGMENT_LIST",
        "GLIMMER_HASH_PAIR_LIST",
        // Bogus nodes
        "GLIMMER_BOGUS",
        "GLIMMER_BOGUS_STATEMENT",
        "GLIMMER_BOGUS_EXPRESSION",
    ],
};
