use crate::kind_src::KindsSrc;

pub const MARKDOWN_KINDS_SRC: KindsSrc = KindsSrc {
    punct: &[
        ("<", "L_ANGLE"),
        (">", "R_ANGLE"),
        ("(", "L_PAREN"),
        (")", "R_PAREN"),
        ("[", "L_BRACK"),
        ("]", "R_BRACK"),
        ("/", "SLASH"),
        ("=", "EQ"),
        ("!", "BANG"),
        ("-", "MINUS"),
        ("*", "STAR"),
        ("+", "PLUS"),
        ("**", "DOUBLE_STAR"),
        ("`", "BACKTICK"),
        ("```", "TRIPLE_BACKTICK"),
        ("~", "TILDE"),
        ("~~~", "TRIPLE_TILDE"),
        ("   ", "WHITESPACE3"),
        ("_", "UNDERSCORE"),
        ("__", "DOUBLE_UNDERSCORE"),
        ("#", "HASH"),
        (",", "COMMA"),
        (":", "COLON"),
    ],
    keywords: &["null"],
    literals: &[
        "MD_HARD_LINE_LITERAL",
        "MD_SOFT_BREAK_LITERAL",
        "MD_TEXTUAL_LITERAL",
        "MD_STRING_LITERAL",
        "MD_INDENT_CHUNK_LITERAL",
        "MD_THEMATIC_BREAK_LITERAL",
        "MD_SETEXT_UNDERLINE_LITERAL",
        "MD_ORDERED_LIST_MARKER",
        "MD_ERROR_LITERAL",
        "MD_ENTITY_LITERAL",
        "MD_QUOTE_PRE_MARKER_INDENT",
        "MD_QUOTE_POST_MARKER_SPACE",
    ],
    tokens: &["ERROR_TOKEN", "NEWLINE", "WHITESPACE", "TAB"],
    nodes: &[
        // Bogus nodes
        "BOGUS",
        "MD_BOGUS",
        "MD_BOGUS_BULLET",
        // node
        "MD_DOCUMENT",
        "MD_BLOCK_LIST",
        "MD_HASH_LIST",
        "MD_HASH",
        "MD_HEADER",
        "MD_INDENT_CODE_BLOCK",
        "MD_FENCED_CODE_BLOCK",
        "MD_CODE_NAME_LIST",
        "MD_HTML_BLOCK",
        "MD_LINK_BLOCK",
        "MD_LINK_REFERENCE_DEFINITION",
        "MD_LINK_LABEL",
        "MD_LINK_DESTINATION",
        "MD_LINK_TITLE",
        "MD_QUOTE",
        "MD_QUOTE_PREFIX",
        "MD_QUOTE_INDENT",
        "MD_QUOTE_INDENT_LIST",
        "MD_ORDERED_LIST_ITEM",
        "MD_BULLET_LIST_ITEM",
        "MD_BULLET_LIST",
        "MD_PARAGRAPH",
        "MD_INLINE_ITEM_LIST",
        "MD_INLINE_EMPHASIS",
        "MD_INLINE_ITALIC",
        "MD_INLINE_CODE",
        "MD_BULLET",
        "MD_INLINE_LINK",
        "MD_INLINE_IMAGE",
        "MD_REFERENCE_LINK",
        "MD_REFERENCE_IMAGE",
        "MD_REFERENCE_LINK_LABEL",
        "MD_AUTOLINK",
        "MD_INLINE_HTML",
        "MD_ENTITY_REFERENCE",
        "MD_INLINE_IMAGE_ALT",
        "MD_INDENTED_CODE_LINE",
        "MD_INLINE_IMAGE_LINK",
        "MD_INLINE_IMAGE_SOURCE",
        "MD_INDENTED_CODE_LINE_LIST",
        "MD_HARD_LINE",
        "MD_SOFT_BREAK",
        "MD_TEXTUAL",
        "MD_SETEXT_HEADER",
        "MD_STRING",
        "MD_INDENT",
        "MD_THEMATIC_BREAK_BLOCK",
        "MD_NEWLINE",
    ],
};
