use crate::kind_src::KindsSrc;

pub const TOML_KINDS_SRC: KindsSrc = KindsSrc {
    punct: &[
        ("=", "EQ"),
        (".", "DOT"),
        (",", "COMMA"),
        ("[", "L_BRACK"),
        ("]", "R_BRACK"),
        ("{", "L_CURLY"),
        ("}", "R_CURLY"),
    ],
    keywords: &[],
    literals: &[
        "TOML_BARE_KEY",
        "TOML_BASIC_STRING",
        "TOML_LITERAL_STRING",
        "TOML_INTEGER",
        "TOML_FLOAT",
        "TOML_BOOLEAN",
        "TOML_OFFSET_DATE_TIME",
        "TOML_LOCAL_DATE_TIME",
        "TOML_LOCAL_DATE",
        "TOML_LOCAL_TIME",
    ],
    tokens: &["ERROR_TOKEN", "NEWLINE", "WHITESPACE", "COMMENT"],
    nodes: &[
        "TOML_ROOT",
        "TOML_ITEM_LIST",
        "TOML_KEY_VALUE",
        "TOML_TABLE",
        "TOML_ARRAY_TABLE",
        "TOML_KEY",
        "TOML_KEY_SEGMENT_LIST",
        "TOML_KEY_SEGMENT",
        "TOML_STRING_VALUE",
        "TOML_INTEGER_VALUE",
        "TOML_FLOAT_VALUE",
        "TOML_BOOLEAN_VALUE",
        "TOML_OFFSET_DATE_TIME_VALUE",
        "TOML_LOCAL_DATE_TIME_VALUE",
        "TOML_LOCAL_DATE_VALUE",
        "TOML_LOCAL_TIME_VALUE",
        "TOML_ARRAY",
        "TOML_ARRAY_ELEMENT_LIST",
        "TOML_INLINE_TABLE",
        "TOML_INLINE_TABLE_ELEMENT_LIST",
        "TOML_BOGUS",
        "TOML_BOGUS_VALUE",
    ],
};
