use std::path::PathBuf;

use anyhow::{Context, Ok, Result};
use quote::quote;

mod paths {
    pub const DERIVED_CORE_PROPERTIES: &str = "target/DerivedCoreProperties-17.0.0.txt";
    pub const DERIVED_GENERAL_CATEGORY: &str = "target/DerivedGeneralCategory-17.0.0.txt";
    pub const EAST_ASIAN_WIDTH: &str = "target/EastAsianWidth-17.0.0.txt";
    pub const EMOJI_DATA: &str = "target/emoji-data-17.0.txt";
    pub const SCRIPTS: &str = "target/Scripts-17.0.0.txt";
    pub const TABLES: &str = "crates/biome_unicode_table/src/tables.rs";
}

const UNICODE_VERSION: &str = "17.0.0";
const EMOJI_VERSION: &str = "17.0";
const UCD_URL: &str = "https://www.unicode.org/Public/17.0.0/ucd";

pub fn generate_tables() -> Result<()> {
    let derived_core_properties = Properties::cached_or_fetch(
        paths::DERIVED_CORE_PROPERTIES,
        &format!("{UCD_URL}/DerivedCoreProperties.txt"),
        UNICODE_VERSION,
        1_134_783,
    )?;

    let properties = ["ID_Continue", "ID_Start"]
        .iter()
        .map(|property| {
            let ranges = derived_core_properties
                .extract(&[*property])?
                .into_iter()
                .map(|(start, end)| quote! { (#start, #end) })
                .collect::<Vec<_>>();

            let fn_ident = quote::format_ident!("{}", property);
            let table_ident = quote::format_ident!("{}_table", property);

            Ok(quote! {
                pub const #table_ident: &[(char, char)] = &[
                    #(#ranges),*
                ];

                pub fn #fn_ident(c: char) -> bool { super::bsearch_range_table(c, #table_ident) }
            })
        })
        .collect::<Result<Vec<_>, _>>()?;

    let east_asian_width = Properties::cached_or_fetch(
        paths::EAST_ASIAN_WIDTH,
        &format!("{UCD_URL}/EastAsianWidth.txt"),
        UNICODE_VERSION,
        201_595,
    )?
    .extract(&["F", "W", "H"])?;
    let hangul = Properties::cached_or_fetch(
        paths::SCRIPTS,
        &format!("{UCD_URL}/Scripts.txt"),
        UNICODE_VERSION,
        192_460,
    )?
    .extract(&["Hangul"])?;
    let emoji = Properties::cached_or_fetch(
        paths::EMOJI_DATA,
        &format!("{UCD_URL}/emoji/emoji-data.txt"),
        EMOJI_VERSION,
        107_324,
    )?
    .extract(&["Emoji"])?;
    let punctuation = Properties::cached_or_fetch(
        paths::DERIVED_GENERAL_CATEGORY,
        &format!("{UCD_URL}/extracted/DerivedGeneralCategory.txt"),
        UNICODE_VERSION,
        277_514,
    )?
    .extract(&["Pc", "Pd", "Pe", "Pf", "Pi", "Po", "Ps"])?;
    let default_ignorable = derived_core_properties.extract(&["Default_Ignorable_Code_Point"])?;

    let cjk_segment_break_character = collect_ranges(|character| {
        contains(&east_asian_width, character)
            && !contains(&hangul, character)
            && !contains(&emoji, character)
            && character != '\u{20a9}'
    });
    let cjk_punctuation = collect_ranges(|character| {
        contains(&east_asian_width, character)
            && (contains(&punctuation, character) || matches!(character, '\u{ff5e}' | '\u{3000}'))
            && character != '\u{20a9}'
    });

    let cjk_segment_break_character = format_table(
        "is_cjk_segment_break_character",
        cjk_segment_break_character,
    );
    let cjk_punctuation = format_table("is_cjk_punctuation", cjk_punctuation);
    let default_ignorable = format_table("is_default_ignorable_code_point", default_ignorable);

    let unicode_version_doc = format!("Generated from Unicode {UNICODE_VERSION}.");
    let tokens = quote! {
        //! Autogenerated file, do not edit by hand.
        //! Run `cargo codegen unicode` and recommit this file when Unicode support has changed.
        #![doc = #unicode_version_doc]
        #![allow(missing_docs, non_upper_case_globals, non_snake_case)]

        fn bsearch_range_table(c: char, r: &[(char,char)]) -> bool {
            use core::cmp::Ordering::{Equal, Less, Greater};
            r.binary_search_by(|&(lo,hi)| {
                // Because ASCII ranges are at the start of the tables, a search for an
                // ASCII char will involve more `Greater` results (i.e. the `(lo,hi)`
                // table entry is greater than `c`) than `Less` results. And given that
                // ASCII chars are so common, it makes sense to favor them. Therefore,
                // the `Greater` case is tested for before the `Less` case.
                if lo > c { Greater }
                else if hi < c { Less }
                else { Equal }
            }).is_ok()
        }

        pub mod derived_property {
            #(#properties)*
        }

        pub mod html {
            #cjk_segment_break_character
            #cjk_punctuation
            #default_ignorable
        }
    };

    let pretty = xtask_glue::reformat(tokens)?;

    std::fs::write(xtask_glue::project_root().join(paths::TABLES), pretty)?;

    Ok(())
}

fn format_table(name: &str, ranges: Vec<(char, char)>) -> proc_macro2::TokenStream {
    let function = quote::format_ident!("{name}");
    let table = quote::format_ident!("{name}_table");
    let ranges = ranges
        .into_iter()
        .map(|(start, end)| quote! { (#start, #end) });

    quote! {
        const #table: &[(char, char)] = &[#(#ranges),*];

        pub fn #function(c: char) -> bool { super::bsearch_range_table(c, #table) }
    }
}

fn contains(ranges: &[(char, char)], character: char) -> bool {
    ranges
        .binary_search_by(|&(start, end)| {
            if start > character {
                std::cmp::Ordering::Greater
            } else if end < character {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

fn collect_ranges(predicate: impl Fn(char) -> bool) -> Vec<(char, char)> {
    let mut ranges: Vec<(char, char)> = Vec::new();

    for code_point in 0..=0x0010_ffff {
        let Some(character) = char::from_u32(code_point) else {
            continue;
        };
        if !predicate(character) {
            continue;
        }

        if let Some((_, end)) = ranges.last_mut()
            && (*end as u32) + 1 == code_point
        {
            *end = character;
        } else {
            ranges.push((character, character));
        }
    }

    ranges
}

struct Properties {
    raw: String,
    cache_path: &'static str,
}

impl Properties {
    /// Retrieves properties for `expected_version` from cache or the Unicode website.
    /// # Errors
    /// Return an error if reading cache or fetching fresh data from the unicode website fails.
    pub fn cached_or_fetch(
        cache_path: &'static str,
        source_url: &str,
        expected_version: &str,
        expected_size: usize,
    ) -> Result<Self> {
        Self::from_cache(cache_path)
            .and_then(|properties| properties.validate(expected_version, expected_size))
            .or_else(|_| {
                let fetched = Self::fetch(cache_path, source_url)?
                    .validate(expected_version, expected_size)?;
                fetched.save_cache()?;
                Ok(fetched)
            })
    }

    fn validate(self, expected_version: &str, expected_size: usize) -> Result<Self> {
        anyhow::ensure!(
            self.raw
                .lines()
                .take(10)
                .any(|line| line.contains(expected_version)),
            "{} does not contain Unicode version {expected_version}",
            self.path().display()
        );
        anyhow::ensure!(
            self.raw.len() == expected_size,
            "{} has size {}, expected {expected_size}",
            self.path().display(),
            self.raw.len()
        );

        Ok(self)
    }

    fn path(&self) -> PathBuf {
        xtask_glue::project_root().join(self.cache_path)
    }

    /// Retrieve properties from the unicode website.
    /// # Errors
    /// Return an error if the HTTP request fails.
    fn fetch(cache_path: &'static str, source_url: &str) -> Result<Self> {
        let raw = ureq::get(source_url).call()?.into_body().read_to_string()?;

        println!("Loaded properties from `unicode.org`");

        Ok(Self { raw, cache_path })
    }

    /// Retrieve properties from cache, see [`Self::save_cache`].
    /// # Errors
    /// Return an error if the cache file couldn't be read.
    fn from_cache(cache_path: &'static str) -> Result<Self> {
        let path = xtask_glue::project_root().join(cache_path);
        let raw = std::fs::read_to_string(&path)?;

        println!("Loaded properties from cache ({})", path.display());

        Ok(Self { raw, cache_path })
    }

    /// Save the properties on disk for later usage, see [`Self::from_cache`].
    /// # Errors
    /// Return an error if saving to disk fails.
    fn save_cache(&self) -> Result<()> {
        let path = self.path();
        std::fs::write(&path, &self.raw)?;

        println!("Saved properties to cache ({})", path.display());

        Ok(())
    }

    /// Extract code points matching one of the specified `properties`.
    /// The returned `Vec` is sorted and sequential code points are collapsed.
    /// # Errors
    /// Return an error if parsing fails.
    pub fn extract(&self, properties: &[&str]) -> Result<Vec<(char, char)>> {
        fn parse_code_point(input: &str) -> Result<char> {
            char::from_u32(
                u32::from_str_radix(input, 16)
                    .with_context(|| format!("unable to parse `{}` as a code point", input))?,
            )
            .ok_or_else(|| anyhow::anyhow!("invalid char `{}`", input))
        }

        for property in properties {
            anyhow::ensure!(
                self.raw
                    .lines()
                    .any(|line| line.split('#').next().is_some_and(|line| line
                        .split(';')
                        .skip(1)
                        .any(|field| field.trim() == *property))),
                "{} does not contain property {property}",
                self.path().display()
            );
        }

        let mut ranges = self
            .raw
            .lines()
            .filter_map(|line| {
                // Discard comments.
                let line = line.split('#').next()?;

                // https://www.unicode.org/reports/tr44/#Data_Fields
                let mut fields = line.split(';');

                // First field is a code point or range.
                let code_point_or_range = fields.next()?.trim();

                // Check if the remaining fields contain a requested property.
                if fields.any(|field| properties.contains(&field.trim())) {
                    Some(code_point_or_range)
                } else {
                    None
                }
            })
            .map(
                |code_point_or_range| match code_point_or_range.split_once("..") {
                    Some((start, end)) => Ok((parse_code_point(start)?, parse_code_point(end)?)),
                    None => {
                        let code_point = parse_code_point(code_point_or_range)?;
                        Ok((code_point, code_point))
                    }
                },
            )
            .collect::<Result<Vec<_>>>()?;

        ranges.sort_unstable_by_key(|range| range.0);

        Ok(ranges
            .into_iter()
            .fold(Vec::<(char, char)>::new(), |mut buffer, (start, end)| {
                if let Some((_, previous_end)) = buffer.last_mut()
                    && start as u32 <= (*previous_end as u32) + 1
                {
                    *previous_end = (*previous_end).max(end);
                } else {
                    buffer.push((start, end));
                }

                buffer
            }))
    }
}
