[package]
name                 = "biome_unicode_table"
version.workspace    = true
authors.workspace    = true
edition.workspace    = true
description          = "Unicode table for JavaScript IDs"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]

[dev-dependencies]

[lints]
workspace = true
