throw Error()
throw (Error)()
throw lib.Error()
throw lib.mod.Error()
throw lib[mod].Error()
throw (/**1**/lib.mod).Error()
throw Error('foo')
throw CustomError('foo')
throw FooBarBazError('foo')
throw ABCError('foo')
throw Abc3Error('foo')
throw TypeError()
throw EvalError()
throw RangeError()
throw ReferenceError()
throw /**1**/ SyntaxError() /**2**/
throw URIError()
throw /**1**/(( /**2**/URIError() ))
throw (( URIError ))()
throw getGlobalThis().Error()
throw utils.getGlobalThis().Error()
throw (( ((getGlobalThis())).Error ))()
throw ( getGlobalThis().Error )()
throw /**1**/ ( /**2**/ getGlobalThis().Error /**3 **/ )()
