use crate::HtmlSyntaxKind::{
    self, ALT_GLYPH_DEF_KW, ALT_GLYPH_ITEM_KW, ALT_GLYPH_KW, ANIMATE_COLOR_KW, ANIMATE_KW,
    ANIMATE_MOTION_KW, ANIMATE_TRANSFORM_KW, CIRCLE_KW, CLIP_PATH_KW, COLOR_PROFILE_KW, CURSOR_KW,
    DEFS_KW, DESC_KW, DISCARD_KW, ELLIPSE_KW, FE_BLEND_KW, FE_COLOR_MATRIX_KW,
    FE_COMPONENT_TRANSFER_KW, FE_COMPOSITE_KW, FE_CONVOLVE_MATRIX_KW, FE_DIFFUSE_LIGHTING_KW,
    FE_DISPLACEMENT_MAP_KW, FE_DISTANT_LIGHT_KW, FE_DROP_SHADOW_KW, FE_FLOOD_KW, FE_FUNC_A_KW,
    FE_FUNC_B_KW, FE_FUNC_G_KW, FE_FUNC_R_KW, FE_GAUSSIAN_BLUR_KW, FE_IMAGE_KW, FE_MERGE_KW,
    FE_MERGE_NODE_KW, FE_MORPHOLOGY_KW, FE_OFFSET_KW, FE_POINT_LIGHT_KW, FE_SPECULAR_LIGHTING_KW,
    FE_SPOT_LIGHT_KW, FE_TILE_KW, FE_TURBULENCE_KW, FILTER_KW, FONT_FACE_FORMAT_KW, FONT_FACE_KW,
    FONT_FACE_NAME_KW, FONT_FACE_SRC_KW, FONT_FACE_URI_KW, FONT_KW, FOREIGN_OBJECT_KW, G_KW,
    GLYPH_KW, GLYPH_REF_KW, HATCH_KW, HATCHPATH_KW, HKERN_KW, IMAGE_KW, LINE_KW,
    LINEAR_GRADIENT_KW, MARKER_KW, MASK_KW, MESH_KW, MESHGRADIENT_KW, MESHPATCH_KW, MESHROW_KW,
    METADATA_KW, MISSING_GLYPH_KW, MPATH_KW, PATH_KW, PATTERN_KW, POLYGON_KW, POLYLINE_KW,
    RADIAL_GRADIENT_KW, RECT_KW, SET_KW, SOLIDCOLOR_KW, STOP_KW, SVG_KW, SWITCH_KW, SYMBOL_KW,
    TEXT_KW, TEXT_PATH_KW, TREF_KW, TSPAN_KW, USE_KW, VIEW_KW, VKERN_KW,
};
use biome_parser::{TokenSet, token_set};

/// Elements that should only appear in SVG contexts, and not in HTML contexts.
pub const SVG_EXCLUSIVE_ELEMENTS: &[&str] = &[
    "altGlyph",
    "altGlyphDef",
    "altGlyphItem",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "circle",
    "clipPath",
    "color-profile",
    "cursor",
    "defs",
    "desc",
    "discard",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDistantLight",
    "feDropShadow",
    "feFlood",
    "feFuncA",
    "feFuncB",
    "feFuncG",
    "feFuncR",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMergeNode",
    "feMorphology",
    "feOffset",
    "fePointLight",
    "feSpecularLighting",
    "feSpotLight",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "font-face",
    "font-face-format",
    "font-face-name",
    "font-face-src",
    "font-face-uri",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "hatch",
    "hatchpath",
    "hkern",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "mesh",
    "meshgradient",
    "meshpatch",
    "meshrow",
    "metadata",
    "missing-glyph",
    "mpath",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "set",
    "solidcolor",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
    "view",
    "vkern",
];

/// Tag-name token kinds for elements that should only appear in SVG contexts.
pub const SVG_EXCLUSIVE_TAG_NAMES: TokenSet<HtmlSyntaxKind> = token_set!(
    ALT_GLYPH_KW,
    ALT_GLYPH_DEF_KW,
    ALT_GLYPH_ITEM_KW,
    ANIMATE_KW,
    ANIMATE_COLOR_KW,
    ANIMATE_MOTION_KW,
    ANIMATE_TRANSFORM_KW,
    CIRCLE_KW,
    CLIP_PATH_KW,
    COLOR_PROFILE_KW,
    CURSOR_KW,
    DEFS_KW,
    DESC_KW,
    DISCARD_KW,
    ELLIPSE_KW,
    FE_BLEND_KW,
    FE_COLOR_MATRIX_KW,
    FE_COMPONENT_TRANSFER_KW,
    FE_COMPOSITE_KW,
    FE_CONVOLVE_MATRIX_KW,
    FE_DIFFUSE_LIGHTING_KW,
    FE_DISPLACEMENT_MAP_KW,
    FE_DISTANT_LIGHT_KW,
    FE_DROP_SHADOW_KW,
    FE_FLOOD_KW,
    FE_FUNC_A_KW,
    FE_FUNC_B_KW,
    FE_FUNC_G_KW,
    FE_FUNC_R_KW,
    FE_GAUSSIAN_BLUR_KW,
    FE_IMAGE_KW,
    FE_MERGE_KW,
    FE_MERGE_NODE_KW,
    FE_MORPHOLOGY_KW,
    FE_OFFSET_KW,
    FE_POINT_LIGHT_KW,
    FE_SPECULAR_LIGHTING_KW,
    FE_SPOT_LIGHT_KW,
    FE_TILE_KW,
    FE_TURBULENCE_KW,
    FILTER_KW,
    FONT_KW,
    FONT_FACE_KW,
    FONT_FACE_FORMAT_KW,
    FONT_FACE_NAME_KW,
    FONT_FACE_SRC_KW,
    FONT_FACE_URI_KW,
    FOREIGN_OBJECT_KW,
    G_KW,
    GLYPH_KW,
    GLYPH_REF_KW,
    HATCH_KW,
    HATCHPATH_KW,
    HKERN_KW,
    IMAGE_KW,
    LINE_KW,
    LINEAR_GRADIENT_KW,
    MARKER_KW,
    MASK_KW,
    MESH_KW,
    MESHGRADIENT_KW,
    MESHPATCH_KW,
    MESHROW_KW,
    METADATA_KW,
    MISSING_GLYPH_KW,
    MPATH_KW,
    PATH_KW,
    PATTERN_KW,
    POLYGON_KW,
    POLYLINE_KW,
    RADIAL_GRADIENT_KW,
    RECT_KW,
    SET_KW,
    SOLIDCOLOR_KW,
    STOP_KW,
    SVG_KW,
    SWITCH_KW,
    SYMBOL_KW,
    TEXT_KW,
    TEXT_PATH_KW,
    TREF_KW,
    TSPAN_KW,
    USE_KW,
    VIEW_KW,
    VKERN_KW,
);

#[cfg(test)]
mod tests {
    use super::{SVG_EXCLUSIVE_ELEMENTS, SVG_EXCLUSIVE_TAG_NAMES};
    use crate::HtmlSyntaxKind;

    #[test]
    fn svg_exclusive_elements_are_sorted() {
        assert!(
            SVG_EXCLUSIVE_ELEMENTS
                .windows(2)
                .all(|elements| elements[0] < elements[1])
        );
    }

    #[test]
    fn svg_exclusive_tag_names_match_elements() {
        for element in SVG_EXCLUSIVE_ELEMENTS {
            let Some(kind) = HtmlSyntaxKind::from_keyword(element) else {
                panic!("`{element}` should be a keyword");
            };
            assert!(
                SVG_EXCLUSIVE_TAG_NAMES.contains(kind),
                "`{element}` should be an SVG-exclusive tag name"
            );
        }

        let tag_name_count = (0..=HtmlSyntaxKind::__LAST as u16)
            .map(HtmlSyntaxKind::from)
            .filter(|kind| SVG_EXCLUSIVE_TAG_NAMES.contains(*kind))
            .count();
        assert_eq!(tag_name_count, SVG_EXCLUSIVE_ELEMENTS.len());
    }
}
