//! Tag-name token classification.
//!
//! Known HTML/SVG tag names are lexed into their keyword token kinds (e.g.
//! `<div>` -> `DIV_KW`, `<circle>` -> `CIRCLE_KW`), so a tag-name check is an
//! `O(1)` token-set membership test instead of a case-insensitive string scan.
//!
//! [`HTML_TAG_NAMES`] is the single source of truth for which keyword kinds are
//! tag names. It is also used by the lexer to reject keywords that are not tag
//! names (e.g. the Svelte `bind` keyword), which then lex as `HTML_UNKNOWN_TAG`.

use crate::HtmlSyntaxKind::{self, *};
use biome_parser::{TokenSet, token_set};

/// Every token kind that may appear as the name of an [`crate::HtmlTagName`]: the
/// known HTML and SVG tag-name keywords, plus the `HTML_UNKNOWN_TAG` fallback for
/// custom/unknown tags.
pub const HTML_TAG_NAMES: TokenSet<HtmlSyntaxKind> = token_set!(
    // Tag names that reuse a kind from an existing (non-tag-section) keyword:
    // `<html>`/`<style>` (HTML) and `<use>`/`<set>`/`<animate>` (SVG).
    HTML_KW,
    STYLE_KW,
    USE_KW,
    SET_KW,
    ANIMATE_KW,
    // HTML tags
    A_KW,
    ABBR_KW,
    ACRONYM_KW,
    ADDRESS_KW,
    AREA_KW,
    ARTICLE_KW,
    ASIDE_KW,
    AUDIO_KW,
    B_KW,
    BASE_KW,
    BASEFONT_KW,
    BDI_KW,
    BDO_KW,
    BGSOUND_KW,
    BIG_KW,
    BLINK_KW,
    BLOCKQUOTE_KW,
    BODY_KW,
    BR_KW,
    BUTTON_KW,
    CANVAS_KW,
    CAPTION_KW,
    CENTER_KW,
    CITE_KW,
    CODE_KW,
    COL_KW,
    COLGROUP_KW,
    DATA_KW,
    DATALIST_KW,
    DD_KW,
    DEL_KW,
    DETAILS_KW,
    DFN_KW,
    DIALOG_KW,
    DIR_KW,
    DIV_KW,
    DL_KW,
    DT_KW,
    EM_KW,
    EMBED_KW,
    FIELDSET_KW,
    FIGCAPTION_KW,
    FIGURE_KW,
    FONT_KW,
    FOOTER_KW,
    FORM_KW,
    FRAME_KW,
    FRAMESET_KW,
    H1_KW,
    H2_KW,
    H3_KW,
    H4_KW,
    H5_KW,
    H6_KW,
    HEAD_KW,
    HEADER_KW,
    HGROUP_KW,
    HR_KW,
    I_KW,
    IFRAME_KW,
    IMAGE_KW,
    IMG_KW,
    INPUT_KW,
    INS_KW,
    KBD_KW,
    KEYGEN_KW,
    LABEL_KW,
    LEGEND_KW,
    LI_KW,
    LINK_KW,
    MAIN_KW,
    MAP_KW,
    MARK_KW,
    MARQUEE_KW,
    MENU_KW,
    MENUITEM_KW,
    META_KW,
    METER_KW,
    NAV_KW,
    NOBR_KW,
    NOEMBED_KW,
    NOFRAMES_KW,
    NOSCRIPT_KW,
    OBJECT_KW,
    OL_KW,
    OPTGROUP_KW,
    OPTION_KW,
    OUTPUT_KW,
    P_KW,
    PARAM_KW,
    PICTURE_KW,
    PLAINTEXT_KW,
    PRE_KW,
    PROGRESS_KW,
    Q_KW,
    RB_KW,
    RP_KW,
    RT_KW,
    RTC_KW,
    RUBY_KW,
    S_KW,
    SAMP_KW,
    SCRIPT_KW,
    SEARCH_KW,
    SECTION_KW,
    SELECT_KW,
    SLOT_KW,
    SMALL_KW,
    SOURCE_KW,
    SPAN_KW,
    STRIKE_KW,
    STRONG_KW,
    SUB_KW,
    SUMMARY_KW,
    SUP_KW,
    SVG_KW,
    TABLE_KW,
    TBODY_KW,
    TD_KW,
    TEMPLATE_KW,
    TEXTAREA_KW,
    TFOOT_KW,
    TH_KW,
    THEAD_KW,
    TIME_KW,
    TITLE_KW,
    TR_KW,
    TRACK_KW,
    TT_KW,
    U_KW,
    UL_KW,
    VAR_KW,
    VIDEO_KW,
    WBR_KW,
    XMP_KW,
    ALT_GLYPH_KW,
    ALT_GLYPH_DEF_KW,
    ALT_GLYPH_ITEM_KW,
    ANIMATE_COLOR_KW,
    ANIMATE_MOTION_KW,
    ANIMATE_TRANSFORM_KW,
    CIRCLE_KW,
    CLIP_PATH_KW,
    COLOR_PROFILE_KW,
    CURSOR_KW,
    DEFS_KW,
    DESC_KW,
    DISCARD_KW,
    ELLIPSE_KW,
    FE_BLEND_KW,
    FE_COLOR_MATRIX_KW,
    FE_COMPONENT_TRANSFER_KW,
    FE_COMPOSITE_KW,
    FE_CONVOLVE_MATRIX_KW,
    FE_DIFFUSE_LIGHTING_KW,
    FE_DISPLACEMENT_MAP_KW,
    FE_DISTANT_LIGHT_KW,
    FE_DROP_SHADOW_KW,
    FE_FLOOD_KW,
    FE_FUNC_A_KW,
    FE_FUNC_B_KW,
    FE_FUNC_G_KW,
    FE_FUNC_R_KW,
    FE_GAUSSIAN_BLUR_KW,
    FE_IMAGE_KW,
    FE_MERGE_KW,
    FE_MERGE_NODE_KW,
    FE_MORPHOLOGY_KW,
    FE_OFFSET_KW,
    FE_POINT_LIGHT_KW,
    FE_SPECULAR_LIGHTING_KW,
    FE_SPOT_LIGHT_KW,
    FE_TILE_KW,
    FE_TURBULENCE_KW,
    FILTER_KW,
    FONT_FACE_KW,
    FONT_FACE_FORMAT_KW,
    FONT_FACE_NAME_KW,
    FONT_FACE_SRC_KW,
    FONT_FACE_URI_KW,
    FOREIGN_OBJECT_KW,
    G_KW,
    GLYPH_KW,
    GLYPH_REF_KW,
    HATCH_KW,
    HATCHPATH_KW,
    HKERN_KW,
    LINE_KW,
    LINEAR_GRADIENT_KW,
    MARKER_KW,
    MASK_KW,
    MESH_KW,
    MESHGRADIENT_KW,
    MESHPATCH_KW,
    MESHROW_KW,
    METADATA_KW,
    MISSING_GLYPH_KW,
    MPATH_KW,
    PATH_KW,
    PATTERN_KW,
    POLYGON_KW,
    POLYLINE_KW,
    RADIAL_GRADIENT_KW,
    RECT_KW,
    SOLIDCOLOR_KW,
    STOP_KW,
    SWITCH_KW,
    SYMBOL_KW,
    TEXT_KW,
    TEXT_PATH_KW,
    TREF_KW,
    TSPAN_KW,
    VIEW_KW,
    VKERN_KW,
    SLOT_KW,
    COMPONENT_KW,
    HTML_UNKNOWN_TAG
);

impl HtmlSyntaxKind {
    /// Returns `true` if this kind can be the name of an [`crate::HtmlTagName`]: a
    /// known HTML/SVG tag-name keyword or the `HTML_UNKNOWN_TAG` fallback.
    pub fn is_html_tag_name(self) -> bool {
        HTML_TAG_NAMES.contains(self)
    }
}

#[cfg(test)]
mod tests {
    use crate::HtmlSyntaxKind;

    /// Sanity-check that the hand-maintained [`super::HTML_TAG_NAMES`] set stays in
    /// sync with the tag keywords: representative HTML/SVG tags (including ones that
    /// reuse an existing keyword kind) must be tag names, and non-tag keywords must
    /// not be. The spec-test fixtures provide broader coverage.
    #[test]
    fn tag_name_classification() {
        for tag in [
            "div",
            "span",
            "a",
            "svg",
            "circle",
            "feGaussianBlur",
            "html",
            "style",
            "use",
            "set",
            "animate",
        ] {
            let kind = HtmlSyntaxKind::from_keyword(tag)
                .unwrap_or_else(|| panic!("`{tag}` should be a keyword"));
            assert!(kind.is_html_tag_name(), "`{tag}` should be a tag name");
        }

        for non_tag in ["bind", "debug", "if", "each"] {
            let kind = HtmlSyntaxKind::from_keyword(non_tag)
                .unwrap_or_else(|| panic!("`{non_tag}` should be a keyword"));
            assert!(
                !kind.is_html_tag_name(),
                "`{non_tag}` should not be a tag name",
            );
        }
    }
}
