//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Build script for #crate_name."]
#![doc = r""]
#![doc = r" THIS FILE IS AUTO-GENERATED by `just gen-analyzer`."]
#![doc = r" DO NOT EDIT MANUALLY!"]
#![doc = r""]
#![doc = r" This build script watches for changes to rule files in group directories"]
#![doc = r#" and "touches" the corresponding group files to trigger recompilation."#]
use std::env;
use std::fs;
use std::io;
use std::path::PathBuf;
use std::time::SystemTime;
fn main() -> io::Result<()> {
    watch_group("assist", "source")?;
    watch_group("lint", "a11y")?;
    watch_group("lint", "nursery")?;
    Ok(())
}
#[doc = r" Watch a specific group directory and touch its group file when changes occur"]
fn watch_group(category: &str, group: &str) -> io::Result<()> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let base_path = PathBuf::from(&manifest_dir).join("src");
    let group_dir = base_path.join(category).join(group);
    let group_file = base_path.join(category).join(format!("{}.rs", group));
    println!("cargo:rerun-if-changed={}", group_dir.display());
    if let Ok(entries) = fs::read_dir(&group_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "rs") {
                println!("cargo:rerun-if-changed={}", path.display());
            }
        }
    }
    touch_file(&group_file)?;
    Ok(())
}
#[doc = r" Update the modification time of a file to trigger recompilation"]
fn touch_file(path: &PathBuf) -> io::Result<()> {
    if !path.exists() {
        return Ok(());
    }
    let now = filetime::FileTime::from_system_time(SystemTime::now());
    filetime::set_file_mtime(path, now)?;
    Ok(())
}
