//! Metadata about unsupported lint rules.

use biome_analyze::RuleSource::*;

use crate::execute::migrate::eslint_to_biome::UnsupportedRule;
use crate::execute::migrate::eslint_to_biome::UnsupportedRuleReason::*;

// Sorted ESLint unsupported rules.
/// The array is sorted to allow binary search.
pub const UNSUPPORTED_RULES: &[UnsupportedRule] = &[
    UnsupportedRule(Eslint("array-bracket-newline"), FormatterCovers),
    UnsupportedRule(Eslint("array-bracket-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("array-element-newline"), FormatterCovers),
    UnsupportedRule(Eslint("arrow-parens"), FormatterOption("arrowParentheses")),
    UnsupportedRule(Eslint("arrow-spacing"), Stylistic),
    UnsupportedRule(Eslint("block-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("brace-style"), Stylistic),
    UnsupportedRule(Eslint("capitalized-comments"), Stylistic),
    UnsupportedRule(Eslint("comma-dangle"), Stylistic),
    UnsupportedRule(Eslint("comma-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("comma-style"), Stylistic),
    UnsupportedRule(Eslint("computed-property-spacing"), Stylistic),
    UnsupportedRule(Eslint("dot-location"), Stylistic),
    UnsupportedRule(Eslint("eol-last"), FormatterCovers),
    UnsupportedRule(Eslint("func-call-spacing"), Stylistic),
    UnsupportedRule(Eslint("function-call-argument-newline"), FormatterCovers),
    UnsupportedRule(Eslint("function-paren-newline"), FormatterCovers),
    UnsupportedRule(Eslint("generator-star"), FormatterCovers),
    UnsupportedRule(Eslint("generator-star-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("implicit-arrow-linebreak"), Stylistic),
    UnsupportedRule(Eslint("indent"), FormatterOption("indentWidth")),
    UnsupportedRule(Eslint("indent-legacy"), FormatterOption("indentWidth")),
    UnsupportedRule(Eslint("jsx-quotes"), FormatterOption("jsxQuoteStyle")),
    UnsupportedRule(Eslint("key-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("keyword-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("line-comment-position"), Stylistic),
    UnsupportedRule(Eslint("linebreak-style"), FormatterOption("lineEnding")),
    UnsupportedRule(Eslint("lines-around-comment"), Stylistic),
    UnsupportedRule(Eslint("lines-around-directive"), Stylistic),
    UnsupportedRule(Eslint("lines-between-class-members"), Stylistic),
    UnsupportedRule(Eslint("max-len"), FormatterOption("lineWidth")),
    UnsupportedRule(Eslint("max-statements-per-line"), FormatterCovers),
    UnsupportedRule(Eslint("multiline-comment-style"), Stylistic),
    UnsupportedRule(Eslint("multiline-ternary"), Stylistic),
    UnsupportedRule(Eslint("new-parens"), FormatterCovers),
    UnsupportedRule(Eslint("newline-after-var"), Stylistic),
    UnsupportedRule(Eslint("newline-before-return"), Stylistic),
    UnsupportedRule(Eslint("newline-per-chained-call"), FormatterCovers),
    UnsupportedRule(Eslint("no-confusing-arrow"), FormatterCovers),
    UnsupportedRule(Eslint("no-extra-parens"), FormatterCovers),
    UnsupportedRule(Eslint("no-extra-semi"), FormatterCovers),
    UnsupportedRule(Eslint("no-floating-decimal"), FormatterCovers),
    UnsupportedRule(Eslint("no-mixed-operators"), Stylistic),
    UnsupportedRule(
        Eslint("no-mixed-spaces-and-tabs"),
        FormatterOption("indentStyle"),
    ),
    UnsupportedRule(Eslint("no-multi-spaces"), FormatterCovers),
    UnsupportedRule(Eslint("no-multiple-empty-lines"), FormatterCovers),
    UnsupportedRule(Eslint("no-space-before-semi"), FormatterCovers),
    UnsupportedRule(Eslint("no-spaced-func"), Stylistic),
    UnsupportedRule(Eslint("no-tabs"), FormatterOption("indentStyle")),
    UnsupportedRule(Eslint("no-trailing-spaces"), FormatterCovers),
    UnsupportedRule(Eslint("no-whitespace-before-property"), Stylistic),
    UnsupportedRule(Eslint("nonblock-statement-body-position"), Stylistic),
    UnsupportedRule(Eslint("object-curly-newline"), FormatterCovers),
    UnsupportedRule(Eslint("object-curly-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("object-property-newline"), FormatterCovers),
    UnsupportedRule(Eslint("one-var-declaration-per-line"), Stylistic),
    UnsupportedRule(
        Eslint("operator-linebreak"),
        FormatterOption("operatorLinebreak"),
    ),
    UnsupportedRule(Eslint("padded-blocks"), Stylistic),
    UnsupportedRule(Eslint("padding-line-between-statements"), Stylistic),
    UnsupportedRule(Eslint("quote-props"), Stylistic),
    UnsupportedRule(Eslint("quotes"), FormatterOption("quoteStyle")),
    UnsupportedRule(Eslint("rest-spread-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("semi"), FormatterOption("semicolons")),
    UnsupportedRule(Eslint("semi-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("semi-style"), FormatterCovers),
    UnsupportedRule(Eslint("space-after-function-name"), Stylistic),
    UnsupportedRule(Eslint("space-after-keywords"), FormatterCovers),
    UnsupportedRule(Eslint("space-before-blocks"), FormatterCovers),
    UnsupportedRule(Eslint("space-before-function-paren"), Stylistic),
    UnsupportedRule(Eslint("space-before-function-parentheses"), Stylistic),
    UnsupportedRule(Eslint("space-before-keywords"), FormatterCovers),
    UnsupportedRule(Eslint("space-in-brackets"), Stylistic),
    UnsupportedRule(Eslint("space-in-parens"), FormatterCovers),
    UnsupportedRule(Eslint("space-infix-ops"), FormatterCovers),
    UnsupportedRule(Eslint("space-return-throw-case"), FormatterCovers),
    UnsupportedRule(Eslint("space-unary-ops"), FormatterCovers),
    UnsupportedRule(Eslint("space-unary-word-ops"), FormatterCovers),
    UnsupportedRule(Eslint("spaced-comment"), Stylistic),
    UnsupportedRule(Eslint("switch-colon-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("template-curly-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("template-tag-spacing"), FormatterCovers),
    UnsupportedRule(Eslint("wrap-iife"), Stylistic),
    UnsupportedRule(Eslint("wrap-regex"), Stylistic),
    UnsupportedRule(Eslint("yield-star-spacing"), FormatterCovers),
    UnsupportedRule(EslintJest("padding-around-after-all-blocks"), Stylistic),
    UnsupportedRule(EslintJest("padding-around-after-each-blocks"), Stylistic),
    UnsupportedRule(EslintJest("padding-around-all"), Stylistic),
    UnsupportedRule(EslintJest("padding-around-before-all-blocks"), Stylistic),
    UnsupportedRule(EslintJest("padding-around-before-each-blocks"), Stylistic),
    UnsupportedRule(EslintJest("padding-around-describe-blocks"), Stylistic),
    UnsupportedRule(EslintJest("padding-around-expect-groups"), Stylistic),
    UnsupportedRule(EslintJest("padding-around-test-blocks"), Stylistic),
    UnsupportedRule(EslintReact("jsx-child-element-spacing"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-closing-bracket-location"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-closing-tag-location"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-curly-newline"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-curly-spacing"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-equals-spacing"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-first-prop-new-line"), Stylistic),
    UnsupportedRule(EslintReact("jsx-indent"), FormatterOption("indentStyle")),
    UnsupportedRule(EslintReact("jsx-indent-props"), Stylistic),
    UnsupportedRule(EslintReact("jsx-max-props-per-line"), Stylistic),
    UnsupportedRule(EslintReact("jsx-newline"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-one-expression-per-line"), Stylistic),
    UnsupportedRule(EslintReact("jsx-props-no-multi-spaces"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-space-before-closing"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-tag-spacing"), FormatterCovers),
    UnsupportedRule(EslintReact("jsx-wrap-multilines"), Stylistic),
    UnsupportedRule(EslintStylistic("array-bracket-newline"), FormatterCovers),
    UnsupportedRule(EslintStylistic("array-bracket-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("array-element-newline"), FormatterCovers),
    UnsupportedRule(
        EslintStylistic("arrow-parens"),
        FormatterOption("arrowParentheses"),
    ),
    UnsupportedRule(EslintStylistic("arrow-spacing"), Stylistic),
    UnsupportedRule(EslintStylistic("block-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("brace-style"), Stylistic),
    UnsupportedRule(EslintStylistic("comma-dangle"), Stylistic),
    UnsupportedRule(EslintStylistic("comma-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("comma-style"), Stylistic),
    UnsupportedRule(EslintStylistic("computed-property-spacing"), Stylistic),
    UnsupportedRule(EslintStylistic("dot-location"), Stylistic),
    UnsupportedRule(EslintStylistic("eol-last"), FormatterCovers),
    UnsupportedRule(EslintStylistic("func-call-spacing"), Stylistic),
    UnsupportedRule(
        EslintStylistic("function-call-argument-newline"),
        FormatterCovers,
    ),
    UnsupportedRule(EslintStylistic("function-paren-newline"), FormatterCovers),
    UnsupportedRule(EslintStylistic("generator-star-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("implicit-arrow-linebreak"), Stylistic),
    UnsupportedRule(EslintStylistic("indent"), FormatterOption("indentWidth")),
    UnsupportedRule(
        EslintStylistic("indent-binary-ops"),
        FormatterOption("indentWidth"),
    ),
    UnsupportedRule(
        EslintStylistic("jsx-child-element-spacing"),
        FormatterCovers,
    ),
    UnsupportedRule(
        EslintStylistic("jsx-closing-bracket-location"),
        FormatterCovers,
    ),
    UnsupportedRule(EslintStylistic("jsx-closing-tag-location"), FormatterCovers),
    UnsupportedRule(EslintStylistic("jsx-curly-newline"), FormatterCovers),
    UnsupportedRule(EslintStylistic("jsx-curly-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("jsx-equals-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("jsx-first-prop-new-line"), Stylistic),
    UnsupportedRule(EslintStylistic("jsx-function-call-newline"), Stylistic),
    UnsupportedRule(EslintStylistic("jsx-indent-props"), Stylistic),
    UnsupportedRule(EslintStylistic("jsx-max-props-per-line"), Stylistic),
    UnsupportedRule(EslintStylistic("jsx-newline"), FormatterCovers),
    UnsupportedRule(EslintStylistic("jsx-one-expression-per-line"), Stylistic),
    UnsupportedRule(
        EslintStylistic("jsx-quotes"),
        FormatterOption("jsxQuoteStyle"),
    ),
    UnsupportedRule(EslintStylistic("jsx-tag-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("jsx-wrap-multilines"), FormatterCovers),
    UnsupportedRule(EslintStylistic("key-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("keyword-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("line-comment-position"), Stylistic),
    UnsupportedRule(
        EslintStylistic("linebreak-style"),
        FormatterOption("lineEnding"),
    ),
    UnsupportedRule(EslintStylistic("lines-around-comment"), Stylistic),
    UnsupportedRule(EslintStylistic("lines-between-class-members"), Stylistic),
    UnsupportedRule(EslintStylistic("list-style"), FormatterCovers),
    UnsupportedRule(EslintStylistic("max-len"), FormatterOption("lineWidth")),
    UnsupportedRule(EslintStylistic("max-statements-per-line"), FormatterCovers),
    UnsupportedRule(EslintStylistic("member-delimiter-style"), FormatterCovers),
    UnsupportedRule(EslintStylistic("multiline-comment-style"), Stylistic),
    UnsupportedRule(EslintStylistic("multiline-ternary"), Stylistic),
    UnsupportedRule(EslintStylistic("new-parens"), FormatterCovers),
    UnsupportedRule(EslintStylistic("newline-per-chained-call"), FormatterCovers),
    UnsupportedRule(EslintStylistic("no-confusing-arrow"), FormatterCovers),
    UnsupportedRule(EslintStylistic("no-extra-parens"), FormatterCovers),
    UnsupportedRule(EslintStylistic("no-extra-semi"), FormatterCovers),
    UnsupportedRule(EslintStylistic("no-floating-decimal"), FormatterCovers),
    UnsupportedRule(EslintStylistic("no-mixed-operators"), Stylistic),
    UnsupportedRule(EslintStylistic("no-multi-spaces"), FormatterCovers),
    UnsupportedRule(EslintStylistic("no-multiple-empty-lines"), FormatterCovers),
    UnsupportedRule(EslintStylistic("no-spaced-func"), Stylistic),
    UnsupportedRule(EslintStylistic("no-tabs"), FormatterOption("indentStyle")),
    UnsupportedRule(EslintStylistic("no-trailing-spaces"), FormatterCovers),
    UnsupportedRule(EslintStylistic("no-whitespace-before-property"), Stylistic),
    UnsupportedRule(
        EslintStylistic("nonblock-statement-body-position"),
        Stylistic,
    ),
    UnsupportedRule(EslintStylistic("object-curly-newline"), FormatterCovers),
    UnsupportedRule(EslintStylistic("object-curly-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("object-property-newline"), FormatterCovers),
    UnsupportedRule(EslintStylistic("one-var-declaration-per-line"), Stylistic),
    UnsupportedRule(
        EslintStylistic("operator-linebreak"),
        FormatterOption("operatorLinebreak"),
    ),
    UnsupportedRule(EslintStylistic("padded-blocks"), Stylistic),
    UnsupportedRule(
        EslintStylistic("padding-line-between-statements"),
        Stylistic,
    ),
    UnsupportedRule(EslintStylistic("quote-props"), Stylistic),
    UnsupportedRule(EslintStylistic("quotes"), FormatterOption("quoteStyle")),
    UnsupportedRule(EslintStylistic("rest-spread-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("space-after-keywords"), FormatterCovers),
    UnsupportedRule(EslintStylistic("space-before-blocks"), FormatterCovers),
    UnsupportedRule(EslintStylistic("space-before-function-paren"), Stylistic),
    UnsupportedRule(
        EslintStylistic("space-before-function-parentheses"),
        Stylistic,
    ),
    UnsupportedRule(EslintStylistic("space-before-keywords"), FormatterCovers),
    UnsupportedRule(EslintStylistic("space-in-brackets"), Stylistic),
    UnsupportedRule(EslintStylistic("space-in-parens"), FormatterCovers),
    UnsupportedRule(EslintStylistic("space-infix-ops"), FormatterCovers),
    UnsupportedRule(EslintStylistic("space-return-throw-case"), FormatterCovers),
    UnsupportedRule(EslintStylistic("space-unary-ops"), FormatterCovers),
    UnsupportedRule(EslintStylistic("space-unary-word-ops"), FormatterCovers),
    UnsupportedRule(EslintStylistic("spaced-comment"), Stylistic),
    UnsupportedRule(EslintStylistic("switch-colon-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("template-curly-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("template-tag-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("type-annotation-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("type-generic-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("type-named-tuple-spacing"), FormatterCovers),
    UnsupportedRule(EslintStylistic("wrap-iife"), Stylistic),
    UnsupportedRule(EslintStylistic("wrap-regex"), Stylistic),
    UnsupportedRule(EslintStylistic("yield-star-spacing"), FormatterCovers),
    UnsupportedRule(EslintTypeScript("brace-style"), Stylistic),
    UnsupportedRule(EslintTypeScript("comma-dangle"), Stylistic),
    UnsupportedRule(EslintTypeScript("comma-spacing"), FormatterCovers),
    UnsupportedRule(EslintTypeScript("func-call-spacing"), FormatterCovers),
    UnsupportedRule(EslintTypeScript("indent"), FormatterOption("indentWidth")),
    UnsupportedRule(EslintTypeScript("keyword-spacing"), FormatterCovers),
    UnsupportedRule(EslintTypeScript("no-extra-parens"), FormatterCovers),
    UnsupportedRule(EslintTypeScript("no-extra-semi"), FormatterCovers),
    UnsupportedRule(EslintTypeScript("object-curly-spacing"), FormatterCovers),
    UnsupportedRule(EslintTypeScript("quotes"), FormatterOption("quoteStyle")),
    UnsupportedRule(EslintTypeScript("semi"), FormatterOption("semicolons")),
    UnsupportedRule(EslintTypeScript("space-before-blocks"), FormatterCovers),
    UnsupportedRule(EslintTypeScript("space-before-function-paren"), Stylistic),
    UnsupportedRule(EslintTypeScript("space-infix-ops"), FormatterCovers),
    UnsupportedRule(EslintUnicorn("empty-brace-spaces"), FormatterCovers),
    UnsupportedRule(EslintVueJs("array-bracket-newline"), FormatterCovers),
    UnsupportedRule(EslintVueJs("array-bracket-spacing"), FormatterCovers),
    UnsupportedRule(EslintVueJs("array-element-newline"), FormatterCovers),
    UnsupportedRule(EslintVueJs("arrow-spacing"), Stylistic),
    UnsupportedRule(EslintVueJs("block-spacing"), FormatterCovers),
    UnsupportedRule(EslintVueJs("block-tag-newline"), Stylistic),
    UnsupportedRule(EslintVueJs("brace-style"), Stylistic),
    UnsupportedRule(EslintVueJs("comma-dangle"), Stylistic),
    UnsupportedRule(EslintVueJs("comma-spacing"), FormatterCovers),
    UnsupportedRule(EslintVueJs("comma-style"), Stylistic),
    UnsupportedRule(EslintVueJs("dot-location"), Stylistic),
    UnsupportedRule(EslintVueJs("first-attribute-linebreak"), Stylistic),
    UnsupportedRule(EslintVueJs("func-call-spacing"), FormatterCovers),
    UnsupportedRule(EslintVueJs("html-closing-bracket-newline"), Stylistic),
    UnsupportedRule(EslintVueJs("html-closing-bracket-spacing"), Stylistic),
    UnsupportedRule(EslintVueJs("html-comment-content-newline"), Stylistic),
    UnsupportedRule(EslintVueJs("html-comment-content-spacing"), Stylistic),
    UnsupportedRule(EslintVueJs("html-comment-indent"), Stylistic),
    UnsupportedRule(EslintVueJs("html-indent"), FormatterCovers),
    UnsupportedRule(EslintVueJs("html-quotes"), Stylistic),
    UnsupportedRule(
        EslintVueJs("html-self-closing"),
        FormatterOption("selfCloseVoidElements"),
    ),
    UnsupportedRule(EslintVueJs("key-spacing"), FormatterCovers),
    UnsupportedRule(EslintVueJs("keyword-spacing"), FormatterCovers),
    UnsupportedRule(EslintVueJs("max-attributes-per-line"), FormatterCovers),
    UnsupportedRule(EslintVueJs("max-len"), FormatterOption("lineWidth")),
    UnsupportedRule(
        EslintVueJs("multiline-html-element-content-newline"),
        Stylistic,
    ),
    UnsupportedRule(EslintVueJs("multiline-ternary"), Stylistic),
    UnsupportedRule(EslintVueJs("mustache-interpolation-spacing"), Stylistic),
    UnsupportedRule(
        EslintVueJs("new-line-between-multi-line-property"),
        Stylistic,
    ),
    UnsupportedRule(EslintVueJs("no-extra-parens"), FormatterCovers),
    UnsupportedRule(EslintVueJs("no-multi-spaces"), FormatterCovers),
    UnsupportedRule(EslintVueJs("no-parsing-error"), FormatterCovers),
    UnsupportedRule(
        EslintVueJs("no-spaces-around-equal-signs-in-attribute"),
        FormatterCovers,
    ),
    UnsupportedRule(EslintVueJs("object-curly-newline"), FormatterCovers),
    UnsupportedRule(EslintVueJs("object-curly-spacing"), FormatterCovers),
    UnsupportedRule(EslintVueJs("object-property-newline"), FormatterCovers),
    UnsupportedRule(
        EslintVueJs("operator-linebreak"),
        FormatterOption("operatorLinebreak"),
    ),
    UnsupportedRule(EslintVueJs("quote-props"), Stylistic),
    UnsupportedRule(EslintVueJs("quotes"), FormatterOption("quoteStyle")),
    UnsupportedRule(
        EslintVueJs("script-indent"),
        FormatterOption("indentScriptAndStyle"),
    ),
    UnsupportedRule(
        EslintVueJs("singleline-html-element-content-newline"),
        Stylistic,
    ),
    UnsupportedRule(EslintVueJs("space-in-parens"), FormatterCovers),
    UnsupportedRule(EslintVueJs("space-infix-ops"), FormatterCovers),
    UnsupportedRule(EslintVueJs("space-unary-ops"), FormatterCovers),
    UnsupportedRule(EslintVueJs("template-curly-spacing"), FormatterCovers),
    UnsupportedRule(HtmlEslint("attrs-newline"), FormatterCovers),
    UnsupportedRule(HtmlEslint("element-newline"), FormatterCovers),
    UnsupportedRule(HtmlEslint("indent"), FormatterOption("indentWidth")),
    UnsupportedRule(HtmlEslint("lowercase"), FormatterCovers),
    UnsupportedRule(HtmlEslint("no-extra-spacing-attrs"), FormatterCovers),
    UnsupportedRule(HtmlEslint("no-extra-spacing-text"), FormatterCovers),
    UnsupportedRule(HtmlEslint("no-multiple-empty-lines"), FormatterCovers),
    UnsupportedRule(HtmlEslint("no-trailing-spaces"), FormatterCovers),
    UnsupportedRule(HtmlEslint("quotes"), FormatterCovers),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_eslint_unsupported_rules_order() {
        let is_sorted = UNSUPPORTED_RULES
            .windows(2)
            .all(|pair| pair[0].0 <= pair[1].0);

        if !is_sorted {
            let mut sorted_rules: Vec<_> = UNSUPPORTED_RULES.iter().collect();
            sorted_rules.sort_by_key(|rule| rule.0);
            panic!(
                "UNSUPPORTED_RULES is not sorted. Expected order:\n{:?}",
                sorted_rules
            );
        }
    }

    #[test]
    fn test_eslint_unsupported_rules_no_duplicates() {
        let mut seen = std::collections::HashSet::new();
        let mut duplicates = Vec::new();

        for rule in UNSUPPORTED_RULES {
            let rule_source = &rule.0;
            if !seen.insert(rule_source) {
                duplicates.push(rule_source);
            }
        }

        if !duplicates.is_empty() {
            panic!(
                "UNSUPPORTED_RULES contains duplicate rule sources:\n{:?}",
                duplicates
            );
        }
    }
}
