[package]
name                 = "biome_manifest"
version              = "0.0.1"
authors.workspace    = true
edition.workspace    = true
description          = "Biome manifest model and loader"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]
biome_console            = { workspace = true }
biome_deserialize        = { workspace = true, features = ["serde"] }
biome_deserialize_macros = { workspace = true }
biome_diagnostics        = { workspace = true }
biome_fs                 = { workspace = true }
biome_json_parser        = { workspace = true }
biome_resolver           = { workspace = true }
biome_rowan              = { workspace = true }
camino                   = { workspace = true }
schemars                 = { workspace = true, optional = true }
serde                    = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[features]
schema = ["dep:schemars"]

[lints]
workspace = true
