<input value />
<input value="string" />
<input {value} />
<input value={value} />
<input value="{value}" />
<input bind:value />
<input bind:value={value} />
<input bind:value="{value}" />
<input class:value />
<input class:value={value} />
<input class:value="{value}" />
<input style:value />
<input style:value={value} />
<input style:value="{value}" />
