//! This represents the core of the Biome workspace. The architecture is based on the
//! actor pattern where mutations happen only in one single place
//!
//! # Server
//!
//! The server is the only type that can contain the whole state of the workspace, and it's
//! the only type that can perform mutations on the said state.
//!
//! This is represented by the [WorkspaceServer].
//!
//! # Owner
//!
//! The owner is the only type that **holds** the server and can perform operations that can mutate
//! the state of the server.
//!
//! These operations can happen directly, or via a thread pool.
//!
//! # Clients
//!
//! Clients are entities that need to talk to the server. Clients can send read-only operations, as well
//! as write operations. Clients must talk with the owner.
//!
//! To talk with the owner, clients receive a [WorkspaceHandle]. A `WorkspaceHandle` is a
//! reference to the server, and it can be cloned, sent to another thread, and so on.
//!
//! # Snapshots
//!
//! Snapshots are a way to save the state of the server. They are [Send], but not [Sync]. They are
//! short-lived and can be used for read-only operations.
//!
//! Snapshots are requested by the clients and generated by the owner.

use biome_resolver::FsWithResolverProxy;
use std::sync::Arc;

mod handle;
mod owner;
mod request;
mod server;
pub(crate) mod snapshots;
mod staged;

pub use handle::{WorkspaceHandle, WorkspaceWatcher};

pub(crate) fn server(
    fs: Arc<dyn FsWithResolverProxy>,
    watcher_tx: crossbeam::channel::Sender<crate::scanner::WatcherInstruction>,
    notification_tx: tokio::sync::watch::Sender<crate::workspace::ServiceNotification>,
    search_provider: Arc<dyn crate::workspace::SearchQuery>,
    threads: Option<usize>,
) -> Box<dyn crate::workspace::ThreadSafeWorkspace> {
    let (handle, _) =
        server_with_watcher(fs, watcher_tx, notification_tx, search_provider, threads);

    Box::new(handle)
}

pub(crate) fn server_with_watcher(
    fs: Arc<dyn FsWithResolverProxy>,
    watcher_tx: crossbeam::channel::Sender<crate::scanner::WatcherInstruction>,
    notification_tx: tokio::sync::watch::Sender<crate::workspace::ServiceNotification>,
    search_provider: Arc<dyn crate::workspace::SearchQuery>,
    threads: Option<usize>,
) -> (WorkspaceHandle, WorkspaceWatcher) {
    let server = crate::workspace::WorkspaceServer::new(
        fs.clone(),
        watcher_tx,
        notification_tx,
        search_provider,
        threads,
    );
    let (owner, handle, watcher) = owner::WorkspaceOwner::new(server, fs, None, threads);

    std::thread::spawn(move || owner.run());

    (handle, watcher)
}
