[package]
name                 = "biome_toml_parser"
version              = "0.0.1"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's TOML parser"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = false

[dependencies]
biome_parser       = { workspace = true }
biome_rowan        = { workspace = true }
biome_toml_factory = { workspace = true }
biome_toml_syntax  = { workspace = true }

[dev-dependencies]
biome_console     = { path = "../biome_console" }
biome_diagnostics = { path = "../biome_diagnostics" }
biome_test_utils  = { path = "../biome_test_utils" }
insta             = { workspace = true }
tests_macros      = { path = "../tests_macros" }

[lints]
workspace = true
