//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Group description generated by proc macro at compile time."]
#![doc = r""]
#![doc = r" To add a new rule, create a `.rs` file or a directory containing"]
#![doc = r" `mod.rs` in the group subdirectory and run `cargo check`. The build"]
#![doc = r" system will automatically discover and register your rule."]
use biome_analyze_macros::declare_group_from_fs;
declare_group_from_fs! { category : "lint" , group : "complexity" }
