//! Nursery lint rules.
//!
//! This file is automatically generated at compile time by reading the
//! filesystem. To add a new rule, simply create a new `.rs` file in the
//! `nursery/` subdirectory and run `cargo check` or `cargo build`.
//!
//! The proc macro will automatically discover and register the new rule.

use biome_analyze_macros::declare_group_from_fs;

declare_group_from_fs! {
    category: "lint",
    group: "nursery"
}
