const a = /*1*/ 'a' + 'b' // comment
const a = 'a' + 'b' + 'c'
const a = 'a' + ('b' + 'c')
const a = ('a' + 'b') + 'c'
const a = foo + 'a' + 'b' + 'c'
const a = (foo + 'a') + ('b' + 'c')
const a = ((foo + 'a') + ('b' + 'c') + 1)
const a = 'a' + `b`
const a = `a` + 'b'
const a = `a` + `b`
const a = 'a' + 1
const a = 1 + '1'
const a = 1 + `1`
const a = `1` + 1
const a = 1 + 1 + ""
const a = "a" + 1e21;
const a = "a" + 0.1e-6;
const a = "a" + -0;
