use std::path::Path;

/// Relative path of the generated global types module from the workspace root.
const OUTPUT_RELATIVE_PATH: &str = "crates/biome_js_type_info/src/generated/global_types.rs";

/// Machine-readable header for the generated global types module.
const GENERATED_FILE_HEADER: &str = "//! Generated by `just gen-global-types`. Do not edit.";

/// Upstream TypeScript repository name shown in the generated source header.
const TYPESCRIPT_SOURCE_NAME: &str = "microsoft/TypeScript";

/// Emits the global types module with LF-normalized output.
///
/// Pin values are safe to interpolate because `SourcePin::new` rejects newlines
/// and block-comment terminators.
pub(super) fn emit_global_types(
    pin: &crate::generate_global_types::SourcePin,
    mode: xtask_glue::Mode,
    workspace_root: &Path,
) -> anyhow::Result<crate::UpdateResult> {
    let path = workspace_root.join(OUTPUT_RELATIVE_PATH);
    let body = generated_body(pin);
    let formatted_body = xtask_glue::reformat_without_preamble(body)?;
    let formatted = format!(
        "{GENERATED_FILE_HEADER}\n//! Source: {TYPESCRIPT_SOURCE_NAME} {} (git commit {})\n\n{formatted_body}",
        pin.tag(),
        pin.sha()
    );
    let formatted = if formatted.contains("\r\n") {
        formatted.replace("\r\n", "\n")
    } else {
        formatted
    };

    crate::update(&path, &formatted, &mode)
}

/// Renders the unformatted Rust body for the generated module, including the
/// pinned tag/SHA and runtime scaffolding constants.
fn generated_body(pin: &crate::generate_global_types::SourcePin) -> String {
    format!(
        r#"// Some generated metadata is emitted before every item has a runtime consumer.
#![allow(dead_code)]

/// TypeScript release tag the generated data was sourced from.
pub(crate) const GENERATED_TYPESCRIPT_TAG: &str = {typescript_tag:?};

/// Commit SHA the [`GENERATED_TYPESCRIPT_TAG`] resolves to.
pub(crate) const GENERATED_TYPESCRIPT_SHA: &str = {typescript_sha:?};

/// Number of predefined global slots populated by the generated module.
pub(crate) const GENERATED_GLOBAL_TYPE_COUNT: usize = 0;

/// Predefined global IDs whose `TypeData` is supplied by this generated module.
pub(crate) const MIGRATED_PREDEFINED_IDS: &[crate::globals::GlobalTypeId] = &[];

/// Registers all generated global type data into the resolver builder.
pub(crate) fn set_generated_global_type_data(builder: &mut crate::globals_builder::GlobalsResolverBuilder) {{
    let _ = builder;
}}
"#,
        typescript_tag = pin.tag(),
        typescript_sha = pin.sha(),
    )
}
