use std::{fmt::Write as _, path::Path};

/// Relative path of the generated global types module from the workspace root.
const OUTPUT_RELATIVE_PATH: &str = "crates/biome_js_type_info/src/generated/global_types.rs";

/// Machine-readable header for the generated global types module.
const GENERATED_FILE_HEADER: &str = "//! Generated by `just gen-global-types`. Do not edit.";

/// Upstream TypeScript repository name shown in the generated source header.
const TYPESCRIPT_SOURCE_NAME: &str = "microsoft/TypeScript";

/// Conservative size hint for one emitted `(<repo_relative>, <sha256_hex>)` row.
const SOURCE_FILE_ROW_ESTIMATED_BYTES: usize = 128;

/// Emits the global types module with LF-normalized output.
///
/// Pin values are safe to interpolate because `SourcePin::new` rejects newlines
/// and block-comment terminators.
pub(super) fn emit_global_types(
    pin: &crate::generate_global_types::SourcePin,
    command_line_parser_sha256: &str,
    source_files: &[super::source::DiscoveredFile],
    collector_summary: &crate::generate_global_types::CollectorSummary,
    mode: xtask_glue::Mode,
    workspace_root: &Path,
) -> anyhow::Result<crate::UpdateResult> {
    let path = workspace_root.join(OUTPUT_RELATIVE_PATH);
    let body = generated_body(
        pin,
        command_line_parser_sha256,
        source_files,
        collector_summary,
    );
    let formatted_body = xtask_glue::reformat_without_preamble(body)?;
    let formatted = format!(
        "{GENERATED_FILE_HEADER}\n//! Source: {TYPESCRIPT_SOURCE_NAME} {} (git commit {})\n\n{formatted_body}",
        pin.tag(),
        pin.sha()
    );
    let formatted = if formatted.contains("\r\n") {
        formatted.replace("\r\n", "\n")
    } else {
        formatted
    };

    crate::update(&path, &formatted, &mode)
}

/// Renders the unformatted Rust body for the generated module, including the
/// pinned tag/SHA, source file table, and collector summary constants.
fn generated_body(
    pin: &crate::generate_global_types::SourcePin,
    command_line_parser_sha256: &str,
    source_files: &[super::source::DiscoveredFile],
    collector_summary: &crate::generate_global_types::CollectorSummary,
) -> String {
    // Write rows into one buffer instead of allocating one `String` per row.
    let mut source_file_rows =
        String::with_capacity(source_files.len() * SOURCE_FILE_ROW_ESTIMATED_BYTES);
    for file in source_files {
        let _ = writeln!(
            &mut source_file_rows,
            "    ({:?}, {:?}),",
            file.repo_relative, file.sha256_hex
        );
    }

    format!(
        r#"// Some generated metadata is emitted before every item has a runtime consumer.
#![allow(dead_code)]

/// TypeScript release tag the generated data was sourced from.
pub(crate) const GENERATED_TYPESCRIPT_TAG: &str = {typescript_tag:?};

/// Commit SHA the [`GENERATED_TYPESCRIPT_TAG`] resolves to.
pub(crate) const GENERATED_TYPESCRIPT_SHA: &str = {typescript_sha:?};

/// SHA-256 digest of TypeScript's command-line parser source.
pub(crate) const COMMAND_LINE_PARSER_SHA256: &str = {command_line_parser_sha256:?};

/// Source files included in the generated global types data, in TypeScript Program order.
pub(crate) const GENERATED_SOURCE_FILES: &[(&str, &str)] = &[
{source_file_rows}];

/// Declarations collected from the pinned TypeScript source profile.
pub(crate) const GENERATED_COLLECTED_DECLARATION_COUNT: usize = {declaration_count};

/// Coverage accounting outcomes collected from the pinned TypeScript source profile.
pub(crate) const GENERATED_COVERAGE_OUTCOME_COUNT: usize = {coverage_outcome_count};

/// SHA-256 digest of collected declaration records and coverage outcomes.
pub(crate) const GENERATED_COLLECTOR_OUTPUT_SHA256: &str = {collector_output_sha256:?};

/// Number of predefined global slots populated by the generated module.
pub(crate) const GENERATED_GLOBAL_TYPE_COUNT: usize = 0;

/// Predefined global IDs whose `TypeData` is supplied by this generated module.
pub(crate) const MIGRATED_PREDEFINED_IDS: &[crate::globals::GlobalTypeId] = &[];

/// Registers all generated global type data into the resolver builder.
pub(crate) fn set_generated_global_type_data(builder: &mut crate::globals_builder::GlobalsResolverBuilder) {{
    let _ = builder;
}}
"#,
        typescript_tag = pin.tag(),
        typescript_sha = pin.sha(),
        command_line_parser_sha256 = command_line_parser_sha256,
        declaration_count = collector_summary.declaration_count,
        coverage_outcome_count = collector_summary.coverage_outcome_count,
        collector_output_sha256 = collector_summary.collector_output_sha256_hex,
    )
}
