//! WASM Component Model plugin engine.
//!
//! [`WasmPluginEngine`] compiles a WASM component, extracts its metadata
//! (target language, rule names, query kinds), and executes per-node checks.
//! It uses `PluginPre` (generated by `wasmtime::component::bindgen!`) to cache
//! linker resolution so that each `check_node()` call only needs a fresh
//! `Store` and instantiation.

use std::collections::HashMap;
use std::fmt;
use std::path::Path;
use std::sync::Arc;

use biome_analyze::{
    PluginCodeAction, PluginDiagnosticEntry, PluginTargetLanguage, PluginTextEdit, RuleDiagnostic,
};
use biome_console::markup;
use biome_diagnostics::{Severity, category};
use biome_js_semantic::SemanticModel;
use biome_module_graph::ModuleResolver;
use biome_rowan::AnySyntaxNode;
use biome_text_size::{TextRange, TextSize};

use crate::host_state::HostState;

/// Normalize a (start, end) pair so that start <= end.
fn normalize_range(start: u32, end: u32) -> (u32, u32) {
    if start <= end {
        (start, end)
    } else {
        (end, start)
    }
}

wasmtime::component::bindgen!({
    path: "wit/biome-plugin.wit",
    world: "plugin",
});

use biome::plugin::host::Host;
use biome::plugin::types::{
    ChildInfo, CommentInfo, Host as TypesHost, NodeInfo, Severity as WitSeverity, TypeInfo,
};

impl TypesHost for HostState {}

impl Host for HostState {
    fn node_kind(&mut self, node: u32) -> u32 {
        Self::node_kind(self, node)
    }

    fn node_text(&mut self, node: u32) -> String {
        Self::node_text(self, node)
    }

    fn node_trimmed_text(&mut self, node: u32) -> String {
        Self::node_trimmed_text(self, node)
    }

    fn node_range(&mut self, node: u32) -> (u32, u32) {
        Self::node_range(self, node)
    }

    fn node_parent(&mut self, node: u32) -> Option<u32> {
        Self::node_parent(self, node)
    }

    fn node_child_count(&mut self, node: u32) -> u32 {
        Self::node_child_count(self, node)
    }

    fn node_nth_child(&mut self, node: u32, index: u32) -> Option<u32> {
        Self::node_nth_child(self, node, index)
    }

    fn node_children(&mut self, node: u32) -> Vec<u32> {
        Self::node_children(self, node)
    }

    fn node_child_by_kind(&mut self, node: u32, kind: u32) -> Option<u32> {
        Self::node_child_by_kind(self, node, kind)
    }

    fn element_is_token(&mut self, handle: u32) -> bool {
        Self::element_is_token(self, handle)
    }

    fn node_children_with_tokens(&mut self, node: u32) -> Vec<u32> {
        Self::node_children_with_tokens(self, node)
    }

    fn node_trimmed_range(&mut self, node: u32) -> (u32, u32) {
        Self::node_trimmed_range(self, node)
    }

    fn resolve_reference(&mut self, node: u32) -> Option<u32> {
        Self::resolve_reference(self, node)
    }

    fn all_references(&mut self, node: u32) -> Vec<u32> {
        Self::all_references(self, node)
    }

    fn is_exported(&mut self, node: u32) -> bool {
        Self::is_exported(self, node)
    }

    fn node_scope(&mut self, node: u32) -> Option<u32> {
        Self::node_scope(self, node)
    }

    fn scope_bindings(&mut self, node: u32) -> Vec<u32> {
        Self::scope_bindings(self, node)
    }

    fn parent_scope_node(&mut self, node: u32) -> Option<u32> {
        Self::parent_scope_node(self, node)
    }

    fn reference_is_read(&mut self, node: u32) -> bool {
        Self::reference_is_read(self, node)
    }

    fn reference_is_write(&mut self, node: u32) -> bool {
        Self::reference_is_write(self, node)
    }

    fn all_read_references(&mut self, node: u32) -> Vec<u32> {
        Self::all_read_references(self, node)
    }

    fn all_write_references(&mut self, node: u32) -> Vec<u32> {
        Self::all_write_references(self, node)
    }

    fn is_imported(&mut self, node: u32) -> bool {
        Self::is_imported(self, node)
    }

    fn scope_get_binding_by_name(&mut self, scope_node: u32, name: String) -> Option<u32> {
        Self::scope_get_binding_by_name(self, scope_node, &name)
    }

    fn is_global_scope(&mut self, scope_node: u32) -> bool {
        Self::is_global_scope(self, scope_node)
    }

    fn scope_ancestors(&mut self, scope_node: u32) -> Vec<u32> {
        Self::scope_ancestors(self, scope_node)
    }

    fn scope_children(&mut self, scope_node: u32) -> Vec<u32> {
        Self::scope_children(self, scope_node)
    }

    fn is_constant_expression(&mut self, node: u32) -> bool {
        Self::is_constant_expression(self, node)
    }

    fn closure_captures(&mut self, node: u32) -> Vec<(u32, u32, bool)> {
        Self::closure_captures(self, node)
    }

    fn expression_type(&mut self, node: u32) -> String {
        Self::expression_type(self, node)
    }

    fn expression_type_info(&mut self, node: u32) -> TypeInfo {
        let (tag, literal_value, union_members) = Self::expression_type_info(self, node);
        TypeInfo {
            tag,
            literal_value,
            union_members,
        }
    }

    fn is_global_reference(&mut self, node: u32) -> bool {
        Self::is_global_reference(self, node)
    }

    fn node_leading_trivia(&mut self, node: u32) -> String {
        Self::node_leading_trivia(self, node)
    }

    fn node_trailing_trivia(&mut self, node: u32) -> String {
        Self::node_trailing_trivia(self, node)
    }

    fn regex_matches(&mut self, text: String, pattern: String) -> bool {
        Self::regex_matches(self, &text, &pattern)
    }

    fn regex_find_all(&mut self, text: String, pattern: String) -> Vec<(u32, u32)> {
        Self::regex_find_all(self, &text, &pattern)
    }

    fn is_reachable(&mut self, node: u32) -> bool {
        Self::is_reachable(self, node)
    }

    fn aria_implicit_role(&mut self, node: u32) -> Option<String> {
        Self::aria_implicit_role(self, node)
    }

    fn file_path(&mut self) -> String {
        Self::file_path(self)
    }

    fn get_node_info(&mut self, node: u32) -> NodeInfo {
        let (kind, trimmed_text, trimmed_range_start, trimmed_range_end, child_count, is_token) =
            Self::node_info(self, node);
        NodeInfo {
            kind,
            trimmed_text,
            trimmed_range_start,
            trimmed_range_end,
            child_count,
            is_token,
        }
    }

    fn node_children_info(&mut self, node: u32) -> Vec<ChildInfo> {
        Self::node_children_info(self, node)
            .into_iter()
            .map(|(handle, kind, trimmed_text)| ChildInfo {
                handle,
                kind,
                trimmed_text,
            })
            .collect()
    }

    fn file_comments(&mut self) -> Vec<CommentInfo> {
        Self::file_comments(self)
            .into_iter()
            .map(|(text, start, end)| CommentInfo { text, start, end })
            .collect()
    }
}

/// Metadata for a single rule within a WASM plugin.
#[derive(Debug, Clone)]
pub struct WasmRuleMetadata {
    pub version: String,
    pub sources: Vec<String>,
    pub recommended: bool,
    pub fix_kind: Option<String>,
    pub category: Option<String>,
    pub domains: Vec<String>,
    pub deprecated: Option<String>,
    pub severity: Option<String>,
    pub issue_number: Option<String>,
}

/// Metadata extracted from a compiled WASM plugin.
#[derive(Debug, Clone)]
pub struct WasmPluginMetadata {
    pub language: String,
    pub rule_names: Vec<String>,
    pub query_kinds_by_rule: HashMap<String, Vec<u32>>,
    pub rule_metadata_by_rule: HashMap<String, WasmRuleMetadata>,
    /// Per-rule trigger strings for host-side pre-filtering. If non-empty,
    /// the host skips calling `check` when the file source doesn't contain
    /// any of these strings (case-insensitive). Empty means "always call".
    pub source_triggers_by_rule: HashMap<String, Vec<String>>,
}

/// Convert WIT check-results into [`PluginDiagnosticEntry`] values.
fn convert_results(
    results: Vec<biome::plugin::types::CheckResult>,
    rule_name: &str,
) -> Vec<PluginDiagnosticEntry> {
    results
        .into_iter()
        .map(|result| {
            let severity = match result.sev {
                WitSeverity::Error => Severity::Error,
                WitSeverity::Warning => Severity::Warning,
                WitSeverity::Information => Severity::Information,
                WitSeverity::Hint => Severity::Hint,
            };

            let (lo, hi) = normalize_range(result.start, result.end);
            let range = TextRange::new(TextSize::from(lo), TextSize::from(hi));

            let mut diagnostic =
                RuleDiagnostic::new(category!("plugin"), range, markup!({ result.message }))
                    .with_severity(severity)
                    .subcategory(rule_name.to_string());

            for label in &result.labels {
                let (lo, hi) = normalize_range(label.start, label.end);
                let label_range = TextRange::new(TextSize::from(lo), TextSize::from(hi));
                diagnostic = diagnostic.label(label_range, markup!({ label.message }));
            }

            for note in &result.notes {
                diagnostic = diagnostic.note(markup!({ note }));
            }
            for warning in &result.warnings {
                diagnostic = diagnostic.warning(markup!({ warning }));
            }

            if result.unnecessary == Some(true) {
                diagnostic = diagnostic.unnecessary();
            }
            if result.deprecated == Some(true) {
                diagnostic = diagnostic.deprecated();
            }
            if result.verbose.unwrap_or(false) {
                diagnostic = diagnostic.verbose();
            }

            let actions: Vec<PluginCodeAction> = result
                .actions
                .into_iter()
                .map(|a| {
                    let applicability = if a.safe {
                        biome_diagnostics::Applicability::Always
                    } else {
                        biome_diagnostics::Applicability::MaybeIncorrect
                    };
                    PluginCodeAction {
                        message: a.message,
                        applicability,
                        edits: a
                            .edits
                            .into_iter()
                            .map(|e| {
                                let (lo, hi) = normalize_range(e.start, e.end);
                                PluginTextEdit {
                                    range: TextRange::new(
                                        TextSize::from(lo),
                                        TextSize::from(hi),
                                    ),
                                    replacement: e.replacement,
                                }
                            })
                            .collect(),
                    }
                })
                .collect();

            PluginDiagnosticEntry {
                diagnostic,
                actions,
            }
        })
        .collect()
}

/// A live WASM plugin instance that can be reused across multiple `check()`
/// calls within the same file, avoiding per-node instantiation overhead.
///
/// Not `Sync` — must be used behind a `Mutex` when shared across threads.
pub struct WasmPluginSession {
    // Note: Debug is manually implemented below since Store/Plugin don't impl Debug.
    store: wasmtime::Store<HostState>,
    bindings: Plugin,
    configured: bool,
    file_path: String,
    language: PluginTargetLanguage,
}

impl fmt::Debug for WasmPluginSession {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("WasmPluginSession")
            .field("file_path", &self.file_path)
            .field("configured", &self.configured)
            .finish_non_exhaustive()
    }
}

impl WasmPluginSession {
    /// The file path this session was created for.
    pub fn file_path(&self) -> &str {
        &self.file_path
    }

    /// Check a new node using the existing instance. Resets the handle table,
    /// refuels the store, and calls `check()` without re-instantiation.
    pub fn check_node(
        &mut self,
        node: AnySyntaxNode,
        rule_name: &str,
        options_json: Option<&str>,
    ) -> Result<Vec<PluginDiagnosticEntry>, wasmtime::Error> {
        // Reset handle table with new root node at handle 0.
        self.store
            .data_mut()
            .reset_for_node(node, self.language);

        self.check_current(rule_name, options_json)
    }

    /// Check the node already at handle 0. Used after `create_session` when
    /// the node is already registered, or after `check_node` resets the table.
    pub fn check_current(
        &mut self,
        rule_name: &str,
        options_json: Option<&str>,
    ) -> Result<Vec<PluginDiagnosticEntry>, wasmtime::Error> {
        // Refuel for the next check.
        self.store.set_fuel(1_000_000)?;

        // Configure on first use within this session.
        if !self.configured {
            if let Some(options) = options_json {
                self.bindings
                    .call_configure(&mut self.store, rule_name, options)?;
            }
            self.configured = true;
        }

        let results = match self.bindings.call_check(&mut self.store, 0, rule_name) {
            Ok(results) => results,
            Err(err) => {
                if let Some(trap) = err.downcast_ref::<wasmtime::Trap>()
                    && *trap == wasmtime::Trap::OutOfFuel
                {
                    return Ok(vec![PluginDiagnosticEntry {
                        diagnostic: RuleDiagnostic::new(
                            category!("plugin"),
                            None::<TextRange>,
                            markup!(
                                "Plugin rule "<Emphasis>{rule_name}</Emphasis>
                                " exceeded its fuel budget and was terminated."
                            ),
                        )
                        .subcategory(rule_name.to_string()),
                        actions: vec![],
                    }]);
                }
                return Err(err);
            }
        };

        Ok(convert_results(results, rule_name))
    }
}

/// Engine for loading and executing WASM plugins.
///
/// Uses `PluginPre` to cache linker import resolution and component
/// instantiation work, so that each `check_node()` call only needs to create
/// a fresh `Store` and instantiate — avoiding repeated type-checking and
/// import binding.
pub struct WasmPluginEngine {
    plugin_pre: PluginPre<HostState>,
}

impl fmt::Debug for WasmPluginEngine {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("WasmPluginEngine")
            .field("plugin_pre", &"<PluginPre>")
            .finish()
    }
}

impl WasmPluginEngine {
    /// Compile a WASM component from raw bytes.
    ///
    /// This pre-instantiates the component with all host and WASI imports
    /// resolved, so that subsequent `metadata()` and `check_node()` calls only
    /// need to create a fresh `Store` and instantiate.
    pub fn new(wasm_bytes: &[u8]) -> Result<Self, wasmtime::Error> {
        let mut config = wasmtime::Config::new();
        config.consume_fuel(true);
        config.wasm_component_model(true);

        let engine = wasmtime::Engine::new(&config)?;
        let component = wasmtime::component::Component::new(&engine, wasm_bytes)?;

        Self::from_component(engine, component)
    }

    /// Compile a WASM component with AOT caching.
    ///
    /// On first call, compiles the WASM bytes and writes the serialized
    /// native code to `<wasm_path>.compiled`. On subsequent calls, loads
    /// the cached artifact directly if the WASM content hasn't changed,
    /// skipping the expensive compilation step.
    ///
    /// # Safety
    /// Uses `unsafe` wasmtime deserialization internally. The cache file
    /// is only ever written by this function from the same wasmtime version,
    /// so this is safe as long as the cache isn't tampered with externally.
    pub fn new_cached(wasm_bytes: &[u8], wasm_path: &Path) -> Result<Self, wasmtime::Error> {
        let mut config = wasmtime::Config::new();
        config.consume_fuel(true);
        config.wasm_component_model(true);

        let engine = wasmtime::Engine::new(&config)?;

        let cache_path = wasm_path.with_extension("wasm.compiled");
        let content_hash = Self::hash_for_cache(wasm_bytes, &engine);

        // Try to load from cache.
        if let Some(component) = Self::load_from_cache(&engine, &cache_path, &content_hash) {
            return Self::from_component(engine, component);
        }

        // Compile from source.
        let component = wasmtime::component::Component::new(&engine, wasm_bytes)?;

        // Write cache (best-effort — failure is not fatal).
        Self::write_cache(&component, &cache_path, &content_hash);

        Self::from_component(engine, component)
    }

    /// Build the engine from an already-compiled component.
    fn from_component(
        engine: wasmtime::Engine,
        component: wasmtime::component::Component,
    ) -> Result<Self, wasmtime::Error> {
        let mut linker = wasmtime::component::Linker::new(&engine);
        Plugin::add_to_linker(&mut linker, |state: &mut HostState| state)?;
        wasmtime_wasi::add_to_linker_sync(&mut linker)?;
        let plugin_pre = PluginPre::new(linker.instantiate_pre(&component)?)?;

        Ok(Self { plugin_pre })
    }

    /// Compute a cache key from WASM content + engine precompile key.
    /// The engine precompile key includes the wasmtime version and all
    /// config flags, ensuring cache invalidation on engine changes.
    fn hash_for_cache(wasm_bytes: &[u8], engine: &wasmtime::Engine) -> [u8; 32] {
        use std::hash::{Hash, Hasher};
        // Hash the engine's precompile compatibility key (encodes wasmtime
        // version + config) together with the WASM content. We use two
        // rounds of DefaultHasher to fill 32 bytes for the cache tag.
        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        engine.precompile_compatibility_hash().hash(&mut hasher);
        hasher.write(wasm_bytes);
        let h1 = hasher.finish();

        let mut hasher2 = std::collections::hash_map::DefaultHasher::new();
        hasher2.write(&h1.to_le_bytes());
        hasher2.write(wasm_bytes);
        let h2 = hasher2.finish();

        let mut out = [0u8; 32];
        out[..8].copy_from_slice(&h1.to_le_bytes());
        out[8..16].copy_from_slice(&h2.to_le_bytes());
        out[16..24].copy_from_slice(&h1.to_be_bytes());
        out[24..32].copy_from_slice(&h2.to_be_bytes());
        out
    }

    /// Try to load a pre-compiled component from the cache file.
    fn load_from_cache(
        engine: &wasmtime::Engine,
        cache_path: &Path,
        expected_hash: &[u8; 32],
    ) -> Option<wasmtime::component::Component> {
        let data = std::fs::read(cache_path).ok()?;
        if data.len() < 32 {
            return None;
        }
        let (stored_hash, serialized) = data.split_at(32);
        if stored_hash != expected_hash {
            return None;
        }
        // SAFETY: The cache was written by this function using the same
        // engine configuration (verified by the hash which includes
        // engine.precompile_compatibility_hash()).
        #[expect(unsafe_code)]
        unsafe {
            wasmtime::component::Component::deserialize(engine, serialized).ok()
        }
    }

    /// Write a compiled component to the cache file (best-effort).
    fn write_cache(
        component: &wasmtime::component::Component,
        cache_path: &Path,
        hash: &[u8; 32],
    ) {
        let Ok(serialized) = component.serialize() else {
            return;
        };
        let mut data = Vec::with_capacity(32 + serialized.len());
        data.extend_from_slice(hash);
        data.extend_from_slice(&serialized);
        let _ = std::fs::write(cache_path, data);
    }

    /// Extract metadata (target language, rule names, query kinds, rule metadata)
    /// from the plugin by instantiating it with a dummy state.
    pub fn metadata(&self) -> Result<WasmPluginMetadata, wasmtime::Error> {
        let mut store = wasmtime::Store::new(self.plugin_pre.engine(), HostState::empty());
        store.set_fuel(1_000_000)?;

        let bindings = self.plugin_pre.instantiate(&mut store)?;
        let language = bindings.call_target_language(&mut store)?;
        let rule_names = bindings.call_rule_names(&mut store)?;

        let mut query_kinds_by_rule = HashMap::new();
        let mut rule_metadata_by_rule = HashMap::new();
        let mut source_triggers_by_rule = HashMap::new();

        for rule_name in &rule_names {
            let query_kinds = bindings.call_query_kinds_for_rule(&mut store, rule_name)?;
            query_kinds_by_rule.insert(rule_name.clone(), query_kinds);

            let meta = bindings.call_rule_metadata(&mut store, rule_name)?;
            rule_metadata_by_rule.insert(
                rule_name.clone(),
                WasmRuleMetadata {
                    version: meta.version,
                    sources: meta.sources,
                    recommended: meta.recommended,
                    fix_kind: meta.fix_kind,
                    category: meta.category,
                    domains: meta.domains,
                    deprecated: meta.deprecated,
                    severity: meta.severity,
                    issue_number: meta.issue_number,
                },
            );

            let triggers =
                bindings.call_source_triggers_for_rule(&mut store, rule_name)?;
            if !triggers.is_empty() {
                source_triggers_by_rule.insert(rule_name.clone(), triggers);
            }
        }

        Ok(WasmPluginMetadata {
            language,
            rule_names,
            query_kinds_by_rule,
            rule_metadata_by_rule,
            source_triggers_by_rule,
        })
    }

    /// Create a reusable session for checking multiple nodes within the same file.
    ///
    /// The session holds a live WASM instance that persists across `check()`
    /// calls, avoiding per-node instantiation overhead.
    pub fn create_session(
        &self,
        node: AnySyntaxNode,
        language: PluginTargetLanguage,
        semantic_model: Option<SemanticModel>,
        module_resolver: Option<Arc<ModuleResolver>>,
        file_path: String,
    ) -> Result<WasmPluginSession, wasmtime::Error> {
        let state = HostState::new(node, language, semantic_model, module_resolver, file_path.clone());
        let mut store = wasmtime::Store::new(self.plugin_pre.engine(), state);
        store.set_fuel(1_000_000)?;
        let bindings = self.plugin_pre.instantiate(&mut store)?;

        Ok(WasmPluginSession {
            store,
            bindings,
            configured: false,
            file_path,
            language,
        })
    }

    /// Check a single matched node and return diagnostics.
    ///
    /// Creates a fresh WASM instance per call. Prefer [`create_session`] +
    /// [`WasmPluginSession::check_node`] for repeated checks within a file.
    #[expect(clippy::too_many_arguments)]
    pub fn check_node(
        &self,
        node: AnySyntaxNode,
        rule_name: &str,
        language: PluginTargetLanguage,
        semantic_model: Option<SemanticModel>,
        module_resolver: Option<Arc<ModuleResolver>>,
        file_path: String,
        options_json: Option<&str>,
    ) -> Result<Vec<PluginDiagnosticEntry>, wasmtime::Error> {
        let mut session = self.create_session(
            node, language, semantic_model, module_resolver, file_path,
        )?;
        // Node is already at handle 0 from create_session — call check directly.
        session.check_current(rule_name, options_json)
    }
}

