[package]
name                 = "biome_markdown_analyze"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true

[dependencies]
biome_analyze            = { workspace = true }
biome_analyze_macros     = { workspace = true }
biome_console            = { workspace = true }
biome_deserialize        = { workspace = true }
biome_deserialize_macros = { workspace = true }
biome_diagnostics        = { workspace = true }
biome_languages          = { workspace = true, features = ["lang_md"] }
biome_markdown_factory   = { workspace = true }
biome_markdown_syntax    = { workspace = true }
biome_rowan              = { workspace = true }
biome_rule_options       = { workspace = true }
biome_suppression        = { workspace = true }
camino                   = { workspace = true }
schemars                 = { workspace = true, optional = true }
serde                    = { workspace = true, features = ["derive"] }

[dev-dependencies]
biome_markdown_parser = { path = "../biome_markdown_parser" }
biome_rowan           = { path = "../biome_rowan" }
biome_test_utils      = { path = "../biome_test_utils", features = ["lang_md"] }
insta                 = { workspace = true }
tests_macros          = { path = "../tests_macros" }

[build-dependencies]
filetime = { workspace = true }

[lints]
workspace = true
