<div onClick={() => {}} />;
<span onClick={() => {}} />;
<big onClick={() => {}} />;
<blockquote onClick={() => {}} />;
<footer onClick={() => {}} />;
<picture onClick={() => {}} />;
<strike onClick={() => {}} />;
<time onClick={() => {}} />;
<div onClick={() => void 0} />;
<div onClick={() => void 0} role={undefined} />;
<div onClick={() => void 0} {...props} />;
<div onKeyUp={() => void 0} aria-hidden={false} />;
<big onClick={() => {}} />;
<body onClick={() => {}} />;
<div onClick={() => {}} />;
<frame onClick={() => {}} />;
<picture onClick={() => {}} />;
<section onClick={() => {}} />;
<span onClick={() => {}} />;
<strike onClick={() => {}} />;
<div onKeyDown={() => {}} />;
<div onKeyPress={() => {}} />;
<div onKeyUp={() => {}} />;
<div onClick={() => {}} />;
<div onMouseDown={() => {}} />;
<div onMouseUp={() => {}} />;


// not generating diagnostics, but should be
<a onClick={() => void 0} />;
<a onClick={() => {}} />;
<a tabIndex="0" onClick={() => void 0} />;
<area onClick={() => {}} />;
<acronym onClick={() => {}} />;
<applet onClick={() => {}} />;
<b onClick={() => {}} />;
<base onClick={() => {}} />;
<bdi onClick={() => {}} />;
<bdo onClick={() => {}} />;
<blink onClick={() => {}} />;
<center onClick={() => {}} />;
<cite onClick={() => {}} />;
<col onClick={() => {}} />;
<colgroup onClick={() => {}} />;
<content onClick={() => {}} />;
<data onClick={() => {}} />;
<font onClick={() => {}} />;
<frameset onClick={() => {}} />;
<head onClick={() => {}} />;
<header onClick={() => {}} />;
<hgroup onClick={() => {}} />;
<i onClick={() => {}} />;
<kbd onClick={() => {}} />;
<keygen onClick={() => {}} />;
<link onClick={() => {}} href="#" />;
<map onClick={() => {}} />;
<meta onClick={() => {}} />;
<noembed onClick={() => {}} />;
<noscript onClick={() => {}} />;
<object onClick={() => {}} />;
<param onClick={() => {}} />;
<q onClick={() => {}} />;
<rp onClick={() => {}} />;
<rt onClick={() => {}} />;
<rtc onClick={() => {}} />;
<s onClick={() => {}} />;
<samp onClick={() => {}} />;
<script onClick={() => {}} />;
<small onClick={() => {}} />;
<source onClick={() => {}} />;
<spacer onClick={() => {}} />;
<style onClick={() => {}} />;
<summary onClick={() => {}} />;
<title onClick={() => {}} />;
<track onClick={() => {}} />;
<tt onClick={() => {}} />;
<u onClick={() => {}} />;
<var onClick={() => {}} />;
<wbr onClick={() => {}} />;
<xmp onClick={() => {}} />;
