name: AgentScan

on:
  pull_request_target:
    types: [ opened, reopened ]
  issues:
    types: [ opened ]

permissions: { }

jobs:
  agentscan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - name: AgentScan
        uses: MatteoGabriele/agentscan-action@2b7e598bd821bc0f4651e985688951930c2f60d0 # v1.12.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
