name: Close issues

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    if: github.repository == 'biomejs/biome'
    runs-on: depot-ubuntu-24.04-arm-small
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.19.0

      - name: Find stale issues
        id: find-stale
        run: echo "issues=$(node --experimental-strip-types .github/scripts/find-stale-issues.ts --token ${{ secrets.GITHUB_TOKEN }})" >> "$GITHUB_OUTPUT"

      - name: Close stale issues
        if: steps.find-stale.outputs.issues != '[]'
        env:
          GH_TOKEN: ${{ secrets.BIOME_ISSUE_AUTOMATION }}
        run: |
          echo '${{ steps.find-stale.outputs.issues }}' | jq -r '.[]' | while read -r issue; do
            gh issue comment "$issue" --repo ${{ github.repository }} --body "This issue has been automatically closed because it has been inactive for more than 3 days and it does not have a minimal reproduction."
            gh issue close "$issue" --repo ${{ github.repository }} --reason "not planned"
            echo "Closed issue #$issue"
          done
