name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          BIOME_REPOSITORY_DISPATCH: ${{ secrets.BIOME_REPOSITORY_DISPATCH }}
          CODSPEED_TOKEN: ${{ secrets.CODSPEED_TOKEN }}
          DISCORD_PREVIEW_RELEASES_HOOK: ${{ secrets.DISCORD_PREVIEW_RELEASES_HOOK }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add BIOME_REPOSITORY_DISPATCH --value "$BIOME_REPOSITORY_DISPATCH" --repo biomejs/biome
          depot ci secrets add CODSPEED_TOKEN --value "$CODSPEED_TOKEN" --repo biomejs/biome
          depot ci secrets add DISCORD_PREVIEW_RELEASES_HOOK --value "$DISCORD_PREVIEW_RELEASES_HOOK" --repo biomejs/biome
  variables:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import variables
        env:
          COPILOT_AGENT_FIREWALL_ALLOW_LIST: ${{ vars.COPILOT_AGENT_FIREWALL_ALLOW_LIST }}
          COPILOT_AGENT_FIREWALL_ENABLED: ${{ vars.COPILOT_AGENT_FIREWALL_ENABLED }}
        run: |
          unset DEPOT_TOKEN
          depot ci vars add COPILOT_AGENT_FIREWALL_ALLOW_LIST --value "$COPILOT_AGENT_FIREWALL_ALLOW_LIST" --repo biomejs/biome
          depot ci vars add COPILOT_AGENT_FIREWALL_ENABLED --value "$COPILOT_AGENT_FIREWALL_ENABLED" --repo biomejs/biome
