name: Update e18e module replacements data

on:
  workflow_dispatch:
  schedule:
    # This cron schedule runs the workflow at midnight (00:00) on Sundays.
    - cron: "0 0 * * 0"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-module-replacements:
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          cache-base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate e18e module replacements data
        run: just gen-module-replacements

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create changeset
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          cat > .changeset/module-replacements-$(date +%s).md << 'EOF'
          ---
          "@biomejs/biome": patch
          ---

          The [noRestrictedDependencies](https://biomejs.dev/linter/rules/no-restricted-dependencies/) rule has been updated with new module replacement data, it should now detect for more relevant replacements.
          EOF

      - name: Create pull request
        id: create-pull-request
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update e18e module replacements data"
          git push origin HEAD:chore/update-module-replacements-data -f
          PR_URL=$(gh pr create --title "chore: update e18e module replacements data" --body "Automated update for module replacements data." --base main)
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

      - name: Auto merge
        if: ${{ steps.create-pull-request.outputs.pr_url != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge "${{ steps.create-pull-request.outputs.pr_url }}" \
            --auto \
            --squash \
            --delete-branch