name: Needs reproduction

on:
  issues:
    types: [labeled]

jobs:
  reply-labeled:
    if: github.repository == 'biomejs/biome'
    runs-on: depot-ubuntu-24.04-arm-small
    steps:
      - name: Remove triaging label
        if: contains(github.event.issue.labels.*.name, 'S-Bug-confirmed') && contains(github.event.issue.labels.*.name, 'S-Needs triage')
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.BIOME_ISSUE_AUTOMATION }}
          script: |
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'S-Needs triage',
              });
              core.info('Removed "S-Needs triage" label');
            } catch (error) {
              if (error.status === 404) {
                core.info('"S-Needs triage" label was not present, skipping');
              } else {
                throw error;
              }
            }

      - name: Needs reproduction
        if: github.event.label.name == 'S-Needs repro'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.BIOME_ISSUE_AUTOMATION }}
          script: |
            const issueAuthor = context.payload.issue.user.login;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: [
                `Hello @${issueAuthor}, please provide a minimal reproduction. You can use one of the following options:`,
                '',
                '- Provide a link to [our playground](https://biomejs.dev/playground), if it\'s applicable.',
                '- Provide a link to GitHub repository. To easily create a reproduction, you can use our interactive CLI via `npm create @biomejs/biome-reproduction`',
                '',
                'Issues marked with `S-Needs repro` will be **closed** if they have **no activity within 3 days**.',
              ].join('\n'),
            });

            core.info('Posted reproduction request comment');

            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'S-Needs triage',
              });
              core.info('Removed "S-Needs triage" label');
            } catch (error) {
              if (error.status === 404) {
                core.info('"S-Needs triage" label was not present, skipping');
              } else {
                throw error;
              }
            }
