name: Publish to crates.io
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crate-publish
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          cache-base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo publish --workspace --token ${{ secrets.CRATES_IO_TOKEN }}
