name: Publish to crates.io
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crate-publish
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          cache-base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo publish --workspace --token ${{ secrets.CRATES_IO_TOKEN }}
