# Jobs run on pull request
name: Pull request
on:
  merge_group:
  pull_request:
    branches:
      - main
      - next
    paths: # Only run when changes are made to rust code or root Cargo
      - "crates/**"
      - "fuzz/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "rustfmt.toml"
      - "deny.toml"
      - ".github/workflows/pull_request.yml"
      - ".github/workflows/release.yml"

# Cancel jobs when the PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTUP_WINDOWS_PATH_ADD_BIN: 1

jobs:
  lint:
    name: Lint project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # we have to also lint on windows because sometimes lints appear only on windows.
          # this particularly occurs when code is conditionally compiled depending on the target os.
          - os: depot-windows-2022
          - os: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          components: clippy
          cache-base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy
        run: cargo lint

  check-dependencies:
    name: Check Dependencies
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          channel: nightly
          bins: cargo-udeps
          cache: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Detect unused dependencies using udeps
        run: cargo +nightly udeps --all-targets --all-features

  deny:
    name: Cargo Deny
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install cargo-deny
        uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: cargo-deny
      - run: cargo deny check bans
      - run: cargo deny check advisories

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: depot-windows-2022-16
          - os: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          cache-base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: cargo test --workspace --features=js_plugin

  e2e-tests:
    name: End-to-end tests
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          cache-base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Biome debug binary
        run: cargo build --bin biome
      - name: Run tests
        run: |
          cd e2e-tests
          sh test-all.sh

  smoke-test-binaries:
    name: Smoke test ${{ matrix.code-target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: depot-windows-2022-16
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: depot-windows-2022-16
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: depot-ubuntu-24.04-16
            target: x86_64-unknown-linux-musl
            code-target: linux-x64-musl
          - os: depot-ubuntu-24.04-arm-16
            target: aarch64-unknown-linux-musl
            code-target: linux-arm64-musl
          - os: depot-macos-14
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: depot-macos-14
            target: aarch64-apple-darwin
            code-target: darwin-arm64
          - os: depot-ubuntu-24.04-16
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
          - os: depot-ubuntu-24.04-arm-4
            target: aarch64-unknown-linux-gnu
            code-target: linux-arm64
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}
      - name: Install musl toolchain
        if: matrix.code-target == 'linux-x64-musl' || matrix.code-target == 'linux-arm64-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - name: Build binary
        run: cargo build -p biome_cli --target ${{ matrix.target }}
        env:
          # Windows binaries can fail to build with a stack overflow error. This increases the stack size to 8MB to mitigate that.
          # We do this because the alternative is to build a release binary, which takes significantly longer to build and is not necessary for a smoke test.
          RUSTFLAGS: ${{ runner.os == 'Windows' && '-C link-arg=/STACK:8388608' || '' }}
      - name: Copy CLI binary
        if: runner.os == 'Windows'
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/debug/biome.exe ./dist/biome-${{ matrix.code-target }}.exe
      - name: Copy CLI binary
        if: runner.os != 'Windows'
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/debug/biome ./dist/biome-${{ matrix.code-target }}
      - name: Smoke test binary (Windows)
        if: matrix.target == 'x86_64-pc-windows-msvc'
        shell: pwsh
        run: .\dist\biome-${{ matrix.code-target }}.exe --version
      - name: Smoke test binary (Unix)
        if: runner.os != 'Windows'
        run: |
          chmod +x ./dist/biome-${{ matrix.code-target }}
          ./dist/biome-${{ matrix.code-target }} --version
      - name: Upload win32-arm64 binary
        if: matrix.target == 'aarch64-pc-windows-msvc'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: smoke-test-win32-arm64
          path: ./dist/biome-win32-arm64.exe
          if-no-files-found: error

  smoke-test-win32-arm64:
    name: Smoke test win32-arm64
    # Depot doesn't have Windows ARM runners.
    runs-on: windows-11-arm
    needs: smoke-test-binaries
    steps:
      - name: Download CLI artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: smoke-test-win32-arm64
      - name: Run --version
        shell: pwsh
        run: .\biome-win32-arm64.exe --version

  documentation:
    name: Documentation
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          cache-base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run doc command
        run: cargo documentation
