# Jobs run on pull request for Node.js APIs
name: Pull request Node.js
on:
  merge_group:
  pull_request:
    branches:
      - main
    paths: # Only run when changes are made to Rust crates or Node.js packages
      - "crates/**"
      - "packages/@biomejs/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "package.json"
      - "pnpm-lock.yaml"
      - "rust-toolchain.toml"
      - ".github/workflows/pull_request_node.yml"

# Cancel jobs when the PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  test-node-api:
    name: Test Node.js API
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          cache-target: release
          cache-base: main
          bins: wasm-bindgen-cli@0.2.117, wasm-opt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build main binary
        run: cargo build -p biome_cli --release
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.14.1
      - name: Cache pnpm modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Install just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

      - name: Build TypeScript code
        # We use the `*-dev` builds below because release builds take very long.
        # The main difference is that release builds run `wasm-opt`, which is
        # responsible for the majority of the time of these builds, but regular
        # PRs of ours don't influence that process anyway, so it feels like a
        # waste of time to run on every PR. It does mean that if `wasm-opt`
        # breaks something, we'll discover it later, possibly when creating a
        # prerelease.
        run: |
          pnpm --filter @biomejs/backend-jsonrpc i
          pnpm --filter @biomejs/backend-jsonrpc run build
          pnpm --filter @biomejs/js-api run build:wasm-bundler-dev
          pnpm --filter @biomejs/js-api run build:wasm-node-dev
          pnpm --filter @biomejs/js-api run build:wasm-web-dev
          pnpm --filter @biomejs/js-api i
          pnpm --filter @biomejs/js-api run build
      - name: Run JS tests
        run: |
          pnpm --filter @biomejs/backend-jsonrpc run test:ci
          pnpm --filter @biomejs/js-api run test:ci
